apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/component: netpol
      app.kubernetes.io/part-of: platform
    includeSelectors: false
    includeTemplates: false

resources:
  - default-deny.yaml
  - allow-ingress-from-nginx.yaml
  - allow-ingress-intra-ns.yaml
  - allow-monitoring-scrape.yaml
  - allow-egress-dns-and-host.yaml
