apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etik-speak-backup-archive
  labels:
    app.kubernetes.io/part-of: etik-speak
    app.kubernetes.io/component: backup-archive
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
