#!/usr/bin/env python3
"""Faz 16.2 — V16 Flyway DDL generator (full impl, Codex iter-4 AGREE).

Codex iter-4 REVISE absorb:
- 23 matched tablo full impl (canonical workcube_mikrolink)
- 17 parametric tablo placeholder (TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED)
- Type mapper robust (decimal scale missing → BLOCKED_UNSUPPORTED)
- FK candidate sadece markdown (SQL üretmez, allowlist)
- Index minimal (PK + partition + content_hash, candidate report)
- Identity: GENERATED BY DEFAULT AS IDENTITY (ALWAYS değil)

Inputs:
- docs/migration/workcube-schema.json (1509 tablo + 26240 kolon)
- docs/migration/report-source-annex.yaml (40 unique tablo allowlist)

Outputs:
- sql/migration/V16__reports.sql (full DDL — 23 tablo + audit + raw + parametric placeholder)
- docs/migration/v16-ddl-review.md (manual review checklist)
- docs/migration/v16-fk-candidates.md (FK candidate report)
- docs/migration/v16-unsupported.md (BLOCKED type/column listesi)
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any
import yaml


# ============================================================================
# Type mapping (Codex iter-1 AGREE + iter-4 robustness)
# ============================================================================

MSSQL_TO_PG_TYPE_BASE = {
    "int": "INTEGER",
    "bigint": "BIGINT",
    "smallint": "SMALLINT",
    "tinyint": "SMALLINT",
    "money": "NUMERIC(19,4)",
    "smallmoney": "NUMERIC(10,4)",
    "float": "DOUBLE PRECISION",
    "real": "REAL",
    "datetime": "TIMESTAMPTZ",
    "datetime2": "TIMESTAMPTZ",
    "smalldatetime": "TIMESTAMPTZ",
    "date": "DATE",
    "time": "TIME",
    "datetimeoffset": "TIMESTAMPTZ",
    "bit": "BOOLEAN",
    "uniqueidentifier": "UUID",
    "binary": "BYTEA",
    "image": "BYTEA",
    "rowversion": "BYTEA",
    "timestamp": "BYTEA",  # MSSQL timestamp ≠ PG TIMESTAMP
    "xml": "TEXT",
    "ntext": "TEXT",
    "text": "TEXT",
    "sql_variant": "TEXT",
    "hierarchyid": "TEXT",
    "geography": "TEXT",
    "geometry": "TEXT",
}

PARTITION_YEARS = [2024, 2025, 2026, 2027, 2028]


# ============================================================================
# Data classes
# ============================================================================

class TableColumn:
    """MSSQL column metadata."""

    def __init__(self, snap: dict):
        self.name = snap["name"]
        self.data_type = snap.get("dataType", "").lower()
        self.max_length = snap.get("maxLength")  # int (-1 for MAX)
        self.nullable = snap.get("nullable", True)
        self.identity = snap.get("identity", False)
        self.pk = snap.get("pk", False)
        self.ordinal = snap.get("ordinal", 0)

    def map_to_pg(self) -> tuple[str, str | None]:
        """Returns (pg_type, blocked_reason). blocked_reason None ise OK."""
        base = self.data_type

        # String types
        if base in {"varchar", "nvarchar", "char", "nchar"}:
            if self.max_length == -1 or self.max_length is None:
                return "TEXT", None
            if self.max_length and self.max_length > 0:
                # nvarchar metadata bazen byte length verir; karakter için /2 (Unicode)
                # Konservatif: olduğu gibi al
                if base.startswith("n") and self.max_length > 1:
                    chars = self.max_length // 2 if self.max_length % 2 == 0 else self.max_length
                else:
                    chars = self.max_length
                pg_base = "VARCHAR" if base in {"varchar", "nvarchar"} else "CHAR"
                return f"{pg_base}({chars})", None
            return "TEXT", None

        if base == "varbinary":
            if self.max_length == -1:
                return "BYTEA", None
            return "BYTEA", None

        # Numeric — decimal/numeric scale eksikliği BLOCKED (Codex iter-4)
        if base in {"decimal", "numeric"}:
            # Snapshot'ta scale yok — finans precision için BLOCKED
            return "NUMERIC", "DECIMAL_SCALE_MISSING"

        # Direct map
        if base in MSSQL_TO_PG_TYPE_BASE:
            return MSSQL_TO_PG_TYPE_BASE[base], None

        # Unknown
        return "TEXT", f"UNKNOWN_TYPE:{base}"


class TableMeta:
    """Per-table metadata (annex + snapshot)."""

    def __init__(self, name: str):
        self.name = name
        self.is_parametric = False
        self.reports: list[str] = []
        self.parametric_schemas: set[str] = set()
        self.category = "?"
        self.snapshot_columns: list[TableColumn] = []
        self.row_count = 0


# ============================================================================
# Loaders
# ============================================================================

def load_inputs(snapshot_path: Path, annex_path: Path) -> tuple[dict, dict]:
    with open(snapshot_path) as f:
        snapshot = json.load(f)
    with open(annex_path) as f:
        annex = yaml.safe_load(f)
    return snapshot, annex


def build_table_metadata(snapshot: dict, annex: dict) -> dict[str, TableMeta]:
    """Annex 2A + snapshot crossreference."""
    metas: dict[str, TableMeta] = {}
    snapshot_tables = snapshot.get("tables", {})

    for r in annex["reports"]:
        rname = r["report"]
        for t in r.get("tables", []):
            tname = t["name"]
            if tname not in metas:
                metas[tname] = TableMeta(tname)
            meta = metas[tname]
            meta.reports.append(rname)
            meta.category = r.get("category", "?")
            if t.get("parametric_schema"):
                meta.is_parametric = True
                meta.parametric_schemas.update(r.get("parametric_schemas", []))

    # Snapshot match
    for tname, meta in metas.items():
        if tname in snapshot_tables:
            tdata = snapshot_tables[tname]
            meta.row_count = tdata.get("rowCount", 0)
            meta.snapshot_columns = [TableColumn(c) for c in tdata.get("columns", [])]
        # Parametric tablolar canonical schema'da yok; placeholder

    return metas


# ============================================================================
# DDL generation
# ============================================================================

AUDIT_DDL = """-- 02 MIGRATION AUDIT
CREATE TABLE migration_audit.migration_runs (
    id BIGSERIAL PRIMARY KEY,
    run_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('initial','final_delta','reconcile_only','dry_run')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING','SUCCESS','FAILED','ABORTED')),
    source_database VARCHAR(128) NOT NULL,
    worker_version VARCHAR(40),
    git_sha VARCHAR(40),
    contract_version VARCHAR(40),
    annex_version VARCHAR(40),
    started_by VARCHAR(128),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    error_summary TEXT,
    notes JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX idx_migration_runs_status ON migration_audit.migration_runs (status, started_at DESC);

CREATE TABLE migration_audit.migration_table_state (
    run_id UUID NOT NULL REFERENCES migration_audit.migration_runs(run_id) ON DELETE CASCADE,
    table_name VARCHAR(128) NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','EXTRACTING','LOADING','VALIDATED','FAILED')),
    rows_extracted BIGINT NOT NULL DEFAULT 0,
    rows_loaded BIGINT NOT NULL DEFAULT 0,
    rows_rejected BIGINT NOT NULL DEFAULT 0,
    last_pk TEXT,
    checksum VARCHAR(64),
    content_hash VARCHAR(64),
    default_partition_rows BIGINT NOT NULL DEFAULT 0,
    batch_no INTEGER NOT NULL DEFAULT 0,
    extract_query_hash VARCHAR(64),
    max_updated_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (run_id, table_name, source_schema, COALESCE(source_year, 0))
);

CREATE INDEX idx_migration_table_state_status ON migration_audit.migration_table_state (status, table_name);

CREATE TABLE migration_audit.migration_rejects (
    id BIGSERIAL PRIMARY KEY,
    run_id UUID NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    source_schema VARCHAR(128),
    source_year SMALLINT,
    source_pk TEXT,
    column_name VARCHAR(128),
    reject_reason VARCHAR(40) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'ERROR' CHECK (severity IN ('WARN','ERROR','CRITICAL')),
    source_value TEXT,
    pg_error_code TEXT,
    pg_error_message TEXT,
    raw_payload JSONB,
    rejected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT
);

CREATE INDEX idx_migration_rejects_run ON migration_audit.migration_rejects (run_id, table_name);
CREATE INDEX idx_migration_rejects_unresolved ON migration_audit.migration_rejects (table_name, rejected_at DESC) WHERE resolved_at IS NULL;
"""


def quote_ident(name: str) -> str:
    """PG identifier — lowercase, double-quote sadece reserved word'de."""
    return name.lower()


def gen_raw_staging(table: TableMeta) -> str:
    tname = quote_ident(table.name)
    return f"""-- raw staging: {table.name}
CREATE TABLE workcube_mssql_raw.{tname} (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_{tname}_run ON workcube_mssql_raw.{tname} (run_id);
"""


def gen_canonical_table(table: TableMeta, blocked: list) -> str:
    """23 matched tablo için full DDL."""
    tname = quote_ident(table.name)
    lines = [f"-- {table.name} (canonical, used by: {', '.join(table.reports[:3])}, rowCount={table.row_count})"]
    lines.append(f"CREATE TABLE workcube_mikrolink.{tname} (")
    lines.append("    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',")

    # Columns
    col_defs = []
    for col in sorted(table.snapshot_columns, key=lambda c: c.ordinal):
        pg_type, block_reason = col.map_to_pg()
        if block_reason:
            blocked.append({
                "table": table.name,
                "column": col.name,
                "mssql_type": col.data_type,
                "max_length": col.max_length,
                "reason": block_reason,
            })
            # BLOCKED kolonları comment olarak ekle
            col_defs.append(f"    -- BLOCKED({block_reason}): {col.name} {col.data_type}(maxLen={col.max_length})")
            continue

        nullable = "" if col.nullable else " NOT NULL"
        identity = " GENERATED BY DEFAULT AS IDENTITY" if col.identity else ""
        col_defs.append(f"    {quote_ident(col.name)} {pg_type}{nullable}{identity},")

    lines.extend(col_defs)
    lines.append("    content_hash VARCHAR(64) NOT NULL,")
    lines.append("    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)")
    lines.append("    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),")
    lines.append("    PRIMARY KEY (migration_row_id)  -- TODO: business PK manual review")
    lines.append(");")
    lines.append("")
    lines.append(f"CREATE INDEX idx_{tname}_hash ON workcube_mikrolink.{tname} (content_hash);")

    return "\n".join(lines) + "\n"


def gen_parametric_placeholder(table: TableMeta) -> str:
    """17 parametric tablo placeholder (snapshot eksik)."""
    tname = quote_ident(table.name)
    schemas = ", ".join(sorted(table.parametric_schemas))
    return f"""-- ===== {table.name} (PARAMETRIC — placeholder) =====
-- Used by: {', '.join(table.reports[:3])}
-- Schemas: {schemas}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.{tname} (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_{tname}_run ON workcube_mssql_raw.{tname} (run_id);

-- workcube_mikrolink.{tname} TODO Faz 16.2.P
"""


# ============================================================================
# Reports (markdown)
# ============================================================================

def gen_review_md(metas: dict, blocked: list) -> str:
    matched = [m for m in metas.values() if not m.is_parametric and m.snapshot_columns]
    parametric = [m for m in metas.values() if m.is_parametric]
    no_snapshot = [m for m in metas.values() if not m.is_parametric and not m.snapshot_columns]

    lines = [
        "# V16 DDL Manual Review (Faz 16.2 Gün 3)\n\n",
        f"> Generator: `scripts/migration/generate_v16_sql.py`\n",
        f"> Codex iter-4 AGREE: 23 matched + 17 parametric placeholder + blocked kolon report\n\n",
        "## Summary\n\n",
        f"- Total tables: {len(metas)}\n",
        f"- Matched canonical (snapshot var): **{len(matched)}**\n",
        f"- Parametric (placeholder): **{len(parametric)}**\n",
        f"- No snapshot (unexpected): {len(no_snapshot)}\n",
        f"- Blocked columns: **{len(blocked)}**\n\n",
        "## Per-table review checklist\n\n",
        "| Table | Type | Columns | Reports | PK status |\n",
        "|---|---|---|---|---|\n",
    ]

    for m in sorted(metas.values(), key=lambda x: x.name):
        if m.is_parametric:
            t = "parametric"
            cols = "?"
            pk = "TODO Faz 16.2.P"
        elif m.snapshot_columns:
            t = "canonical"
            cols = str(len(m.snapshot_columns))
            pk = "surrogate (TODO business PK)"
        else:
            t = "no-snapshot"
            cols = "0"
            pk = "FAIL"
        reports = ", ".join(m.reports[:3])[:60]
        lines.append(f"| `{m.name}` | {t} | {cols} | {reports} | {pk} |\n")

    if blocked:
        lines.append("\n## Blocked columns (manual contract gerek)\n\n")
        lines.append("| Table | Column | MSSQL Type | maxLength | Reason |\n")
        lines.append("|---|---|---|---|---|\n")
        for b in blocked:
            lines.append(f"| `{b['table']}` | `{b['column']}` | `{b['mssql_type']}` | {b['max_length']} | {b['reason']} |\n")

    lines.append("\n## Sıradaki sprint\n\n")
    lines.append("- **Faz 16.2.P Schema Snapshot Enrichment**: schema-service parametric crawl + PK + scale metadata (Codex iter-4 ayrı sprint)\n")
    lines.append("- **Gün 4**: Worker skeleton (Python + pyodbc + COPY)\n")
    lines.append("- **Gün 5-7**: Transform + retry + reconcile + dry-run\n")

    return "".join(lines)


def gen_fk_candidates_md(snapshot: dict, etl_scope: set[str]) -> str:
    relationships = snapshot.get("relationships", [])
    candidates = [r for r in relationships if r.get("fromTable") in etl_scope and r.get("toTable") in etl_scope]

    lines = [
        "# V16 FK Candidates (Faz 16.2 Gün 3)\n\n",
        f"> Codex iter-3+4 verdict: FK MINIMAL — sadece markdown rapor, SQL üretme.\n",
        f"> Reconciliation 16.3.5 authoritative gate.\n\n",
        f"## Summary\n\n",
        f"- Total relationships in snapshot: {len(relationships)}\n",
        f"- Candidates (both ends in ETL scope): **{len(candidates)}**\n\n",
        "## FK candidates within ETL scope (manual review)\n\n",
    ]

    if candidates:
        lines.append("| From | From column | To | To column | Confidence |\n")
        lines.append("|---|---|---|---|---|\n")
        for r in candidates[:50]:
            lines.append(f"| `{r.get('fromTable')}` | `{r.get('fromColumn', '?')}` | `{r.get('toTable')}` | `{r.get('toColumn', '?')}` | {r.get('confidence', 'unknown')} |\n")
        if len(candidates) > 50:
            lines.append(f"\n... + {len(candidates) - 50} more (full list: snapshot relationships scope filtered)\n")
    else:
        lines.append("(No relationships in scope — annex tablolar arasında FK yok)\n")

    lines.append("\n## Karar\n\n")
    lines.append("Codex iter-3 AGREE: FK MINIMAL + NOT VALID + reconciliation authoritative.\n")
    lines.append("Bu liste manuel review için. SQL FK clause **gerekirse** review sonrası V16'a eklenir.\n")
    return "".join(lines)


def gen_unsupported_md(blocked: list) -> str:
    if not blocked:
        return "# V16 Unsupported Columns (boş — tüm kolonlar map'lendi)\n"

    by_reason = defaultdict(list)
    for b in blocked:
        by_reason[b["reason"]].append(b)

    lines = [
        "# V16 Unsupported / Blocked Columns (Faz 16.2 Gün 3)\n\n",
        f"> Codex iter-4 verdict: snapshot eksik metadata → FAIL FAST, BLOCKED kolon DDL'e eklenmez.\n\n",
        f"## Summary\n\n",
        f"- Total blocked: **{len(blocked)}**\n",
    ]
    for reason, items in by_reason.items():
        lines.append(f"- {reason}: {len(items)}\n")
    lines.append("\n## Per-reason detail\n\n")
    for reason, items in sorted(by_reason.items()):
        lines.append(f"### {reason}\n\n")
        lines.append("| Table | Column | MSSQL Type | maxLength |\n|---|---|---|---|\n")
        for b in sorted(items, key=lambda x: (x["table"], x["column"])):
            lines.append(f"| `{b['table']}` | `{b['column']}` | `{b['mssql_type']}` | {b['max_length']} |\n")
        lines.append("\n")
    lines.append("## Resolution\n\n")
    lines.append("- `DECIMAL_SCALE_MISSING`: Workcube admin'den scale netleştirilir (finans precision için kritik)\n")
    lines.append("- `UNKNOWN_TYPE`: Type mapping rule eklenmeli (`MSSQL_TO_PG_TYPE_BASE`)\n")
    lines.append("\nBLOCKED kolonlar **DDL'e eklenmez**, generator output'unda comment olarak tutulur. Manuel resolve sonrası generator rerun.\n")
    return "".join(lines)


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--snapshot", required=True, type=Path)
    parser.add_argument("--annex", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--review-out", required=True, type=Path)
    parser.add_argument("--fk-out", required=True, type=Path)
    parser.add_argument("--unsupported-out", required=True, type=Path)
    args = parser.parse_args()

    snapshot, annex = load_inputs(args.snapshot, args.annex)
    metas = build_table_metadata(snapshot, annex)
    etl_scope = set(metas.keys())

    matched = sum(1 for m in metas.values() if not m.is_parametric and m.snapshot_columns)
    parametric = sum(1 for m in metas.values() if m.is_parametric)
    print(f"ETL scope: {len(etl_scope)} table", file=sys.stderr)
    print(f"  Matched canonical: {matched}", file=sys.stderr)
    print(f"  Parametric placeholder: {parametric}", file=sys.stderr)

    blocked: list[dict] = []

    # ============= V16 SQL =============
    sections: list[str] = [
        "-- Faz 16.2 V16 — generated by scripts/migration/generate_v16_sql.py\n",
        "-- Codex iter-4 AGREE: 23 matched canonical + 17 parametric placeholder\n",
        f"-- Tables: {len(etl_scope)} (matched={matched}, parametric={parametric})\n",
        "\nBEGIN;\n\n",
        "-- 00 EXTENSIONS\nCREATE EXTENSION IF NOT EXISTS citext;\nCREATE EXTENSION IF NOT EXISTS pgcrypto;\n\n",
        "-- 01 SCHEMAS\nCREATE SCHEMA IF NOT EXISTS workcube_mikrolink;\nCREATE SCHEMA IF NOT EXISTS workcube_mssql_raw;\nCREATE SCHEMA IF NOT EXISTS migration_audit;\n\n",
        AUDIT_DDL,
        "\n-- ===== 03 RAW STAGING + 04+05 FINAL TABLES =====\n\n",
    ]

    # Per-table DDL
    for tname in sorted(etl_scope):
        meta = metas[tname]
        if meta.is_parametric:
            sections.append(gen_parametric_placeholder(meta))
        elif meta.snapshot_columns:
            sections.append(gen_raw_staging(meta))
            sections.append("\n")
            sections.append(gen_canonical_table(meta, blocked))
        else:
            sections.append(f"-- WARNING: {tname} no snapshot columns — skipped\n")
        sections.append("\n")

    sections.append("\nCOMMIT;\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(sections))
    print(f"Wrote: {args.out} ({len(open(args.out).read().splitlines())} lines)", file=sys.stderr)

    # ============= Review markdown =============
    args.review_out.parent.mkdir(parents=True, exist_ok=True)
    args.review_out.write_text(gen_review_md(metas, blocked))
    print(f"Wrote: {args.review_out}", file=sys.stderr)

    # ============= FK candidates =============
    args.fk_out.parent.mkdir(parents=True, exist_ok=True)
    args.fk_out.write_text(gen_fk_candidates_md(snapshot, etl_scope))
    print(f"Wrote: {args.fk_out}", file=sys.stderr)

    # ============= Unsupported columns =============
    args.unsupported_out.parent.mkdir(parents=True, exist_ok=True)
    args.unsupported_out.write_text(gen_unsupported_md(blocked))
    print(f"Wrote: {args.unsupported_out} ({len(blocked)} blocked)", file=sys.stderr)

    print("DONE", file=sys.stderr)


if __name__ == "__main__":
    main()
