apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: budget-service
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/part-of: platform
    includeSelectors: false
    includeTemplates: true

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml
