#!/usr/bin/env bash
# scripts/automation/sync-audio-gateway-test-overlay.sh
#
# Faz 24 audio-gateway test overlay staging.
#
# Opens or updates a GitOps-authoritative auto-test-overlay PR that rewrites
# only the audio-gateway-service digest in kustomize/overlays/test. It does not
# mutate k3d-test directly; merge/sync remains the live deployment boundary.

set -euo pipefail

BRANCH="auto-test-overlay/audio-gateway-testai"
KUSTOMIZATION="kustomize/overlays/test/kustomization.yaml"
APPLY_SCRIPT="scripts/automation/apply-test-overlay-digests.py"
GH_REPO="${GITHUB_REPO:-Halildeu/platform-k8s-gitops}"
SERVER_URL="${GITHUB_SERVER_URL:-https://github.com}"
BOT_NAME="platform-automation[bot]"
BOT_EMAIL="platform-automation[bot]@users.noreply.github.com"

: "${IMAGE_DIGEST:?IMAGE_DIGEST env required (sha256:<64hex>)}"

SOURCE_SHA="${SOURCE_SHA:-}"
SOURCE_REF="${SOURCE_REF:-}"
EVIDENCE_URL="${EVIDENCE_URL:-}"
RUN_ID="${RUN_ID:-0}"
RUN_URL="${SERVER_URL}/${GH_REPO}/actions/runs/${RUN_ID}"

if ! [[ "${IMAGE_DIGEST}" =~ ^sha256:[a-f0-9]{64}$ ]]; then
  echo "::error::IMAGE_DIGEST must match ^sha256:[a-f0-9]{64}$: ${IMAGE_DIGEST}"
  exit 1
fi

if [[ ! -f "${APPLY_SCRIPT}" ]]; then
  echo "::error::apply script not found: ${APPLY_SCRIPT}"
  exit 1
fi

DIGEST_MAP=$(jq -cn --arg d "${IMAGE_DIGEST}" '{"audio-gateway-service": $d}')

git fetch origin main --quiet
git checkout -B "${BRANCH}" origin/main --quiet

if ! APPLY_OUT=$(python3 "${APPLY_SCRIPT}" --digest-map "${DIGEST_MAP}" --kustomization "${KUSTOMIZATION}"); then
  echo "::error::audio-gateway digest apply failed"
  exit 1
fi
echo "${APPLY_OUT}"

if git diff --quiet -- "${KUSTOMIZATION}"; then
  echo "[audio-gateway-overlay] test overlay already pins ${IMAGE_DIGEST}; no PR needed"
  exit 0
fi

changed_files=$(git diff --name-only)
if [[ "${changed_files}" != "${KUSTOMIZATION}" ]]; then
  echo "::error::diff-guard: only ${KUSTOMIZATION} may change; got: ${changed_files//$'\n'/, }"
  exit 1
fi

offending=$(git diff -U0 -- "${KUSTOMIZATION}" \
  | grep -E '^[-+]' \
  | grep -vE '^(\+\+\+|---) ' \
  | grep -vE '^[-+][[:space:]]+digest: sha256:[a-f0-9]{64}$' || true)
if [[ -n "${offending}" ]]; then
  echo "::error::diff-guard: non-digest line(s) in the diff:"
  printf '%s\n' "${offending}"
  exit 1
fi

added=$(git diff -U0 -- "${KUSTOMIZATION}" \
  | grep -cE '^\+[[:space:]]+digest: sha256:[a-f0-9]{64}$' || true)
deleted=$(git diff -U0 -- "${KUSTOMIZATION}" \
  | grep -cE '^-[[:space:]]+digest: sha256:[a-f0-9]{64}$' || true)
if [[ "${added}" -ne 1 || "${deleted}" -ne 1 ]]; then
  echo "::error::diff-guard: expected exactly one digest rewrite (+1/-1); got +${added}/-${deleted}"
  exit 1
fi

short_ref="${SOURCE_SHA:-${SOURCE_REF:-audio-gateway}}"
if [[ "${#short_ref}" -gt 12 ]]; then
  short_ref="${short_ref:0:12}"
fi

git config user.name "${BOT_NAME}"
git config user.email "${BOT_EMAIL}"
git add "${KUSTOMIZATION}"
git commit --quiet -m "auto(test-overlay): stage audio-gateway digest ${short_ref}

Stages audio-gateway-service for Faz 24 test overlay via GitOps desired-state.
Generated by ${BASH_SOURCE[0]} from ${RUN_URL}."

git push --force-with-lease origin "HEAD:${BRANCH}" --quiet

existing=$(gh pr list --repo "${GH_REPO}" --head "${BRANCH}" --state open \
  --json number --jq '.[0].number // empty')
if [[ -n "${existing}" ]]; then
  echo "[audio-gateway-overlay] PR #${existing} already open for ${BRANCH}; force-push updated it"
  exit 0
fi

source_line="- Source: ${SOURCE_REF:-N/A}"
if [[ -n "${SOURCE_SHA}" ]]; then
  source_line="- Source sha: \`${SOURCE_SHA}\`"
fi

evidence_line="- Evidence: ${EVIDENCE_URL:-${RUN_URL}}"

BODY=$(cat <<EOF
## Summary

Stages the Faz 24 \`audio-gateway-service\` image digest in
\`${KUSTOMIZATION}\`. This PR does **not** mutate the cluster by itself; the
live boundary remains merge + ArgoCD/test-overlay sync + post-sync evidence.

### Digest change

~~~
${APPLY_OUT}
~~~

${source_line}
- Image digest: \`${IMAGE_DIGEST}\`
${evidence_line}
- Generating run: ${RUN_URL}

## Acceptance boundary

After merge/sync, live acceptance still requires:

- audio-gateway pod imageID equals the pinned digest;
- readiness and stability stay green;
- real desktop consent/session/chunk/finish path works through
  \`https://testai.acik.com/api/v1/audio-gateway\`;
- Direct-STT counters, aggregation windows, RTF, saturation, GPU telemetry, and
  transcript delivery evidence are captured for the Faz 24 latency/accuracy
  gate.

## Boundary declaration (ADR-0011 §2.3)

- [ ] credential-read
- [ ] credential-write
- [x] state-mutation (test cluster)
- [ ] state-mutation (production)
- [ ] boundary-cross
- [ ] user-communication
- [ ] none of the above

This PR stages only the **test** overlay desired-state. It does not touch
production, credentials, or raw transcript/audio evidence.

## Cross-AI

Cross-AI exempt reason: Machine-generated GitOps test-overlay digest staging PR; the workflow only rewrites one bounded digest line and cannot make a peer-review claim.
Automation source: .github/workflows/deploy-backend-testai.yml
Automation evidence: ${RUN_URL}
EOF
)

gh pr create \
  --repo "${GH_REPO}" \
  --head "${BRANCH}" \
  --base main \
  --title "auto(test-overlay): stage audio-gateway digest for Faz 24" \
  --body "${BODY}" \
  --draft

echo "[audio-gateway-overlay] opened PR for ${BRANCH}"
