#!/usr/bin/env bash
set -euo pipefail

# Open or update the desired-state-first frontend promotion PR. This script
# never talks to Kubernetes; ArgoCD reconciliation happens only after review
# and merge through verify-testai-frontend-rollout.yml.

KUSTOMIZATION="kustomize/overlays/test/kustomization.yaml"
APPLY_SCRIPT="scripts/automation/test-overlay-frontend-image.py"
DIFF_GUARD="scripts/automation/validate-test-overlay-frontend-diff.sh"
GH_REPO="${GITHUB_REPO:-Halildeu/platform-k8s-gitops}"
SERVER_URL="${GITHUB_SERVER_URL:-https://github.com}"
BOT_NAME="platform-gitops-automation[bot]"
BOT_EMAIL="platform-gitops-automation[bot]@users.noreply.github.com"

: "${SHA:?SHA env required}"
: "${SHORT_SHA:?SHORT_SHA env required}"
: "${IMAGE:?IMAGE env required}"
: "${IMAGE_TAG:?IMAGE_TAG env required}"
: "${IMAGE_DIGEST:?IMAGE_DIGEST env required}"
: "${GH_TOKEN:?GH_TOKEN must be a platform-gitops-automation GitHub App token}"

RUN_ID="${RUN_ID:-0}"
RUN_ATTEMPT="${RUN_ATTEMPT:-1}"
[[ "$RUN_ID" =~ ^[0-9]+$ && "$RUN_ATTEMPT" =~ ^[0-9]+$ ]] || {
  echo "[frontend-overlay] RUN_ID/RUN_ATTEMPT must be numeric" >&2
  exit 1
}
# Every run-attempt gets an append-only branch. Repository rulesets prohibit
# force-push, and a single reusable branch can be non-fast-forward after merge.
BRANCH="auto-test-frontend/testai-${SHORT_SHA}-${RUN_ID}-${RUN_ATTEMPT}"
RUN_URL="${SERVER_URL}/${GH_REPO}/actions/runs/${RUN_ID}"

git fetch origin main --quiet
git checkout -B "$BRANCH" origin/main --quiet

APPLY_OUT=$(python3 "$APPLY_SCRIPT" apply \
  --kustomization "$KUSTOMIZATION" \
  --sha "$SHA" \
  --short-sha "$SHORT_SHA" \
  --image "$IMAGE" \
  --image-tag "$IMAGE_TAG" \
  --image-digest "$IMAGE_DIGEST")
printf '%s\n' "$APPLY_OUT"

if git diff --quiet -- "$KUSTOMIZATION"; then
  echo "[frontend-overlay] origin/main already contains ${IMAGE_TAG}@${IMAGE_DIGEST}"
  exit 0
fi

bash "$DIFF_GUARD" "$KUSTOMIZATION"

git config user.name "$BOT_NAME"
git config user.email "$BOT_EMAIL"
git add "$KUSTOMIZATION"
git commit --quiet -m "auto(test-overlay): promote frontend ${IMAGE_TAG}

Desired-state-first testai frontend promotion. No direct workload mutation.
Artifact: ${IMAGE}@${IMAGE_DIGEST}
Source: ${SHA}
Run: ${RUN_URL}
Tracked by #2295."
git push origin "HEAD:${BRANCH}" --quiet

# Quoted heredoc is a safety boundary. The PR body contains Markdown backticks;
# an unquoted heredoc executes them as shell command substitutions. In
# particular the generated-by path recursively invoked this script until the
# workflow timed out (run 29534095913). Keep interpolation explicit below.
BODY=$(cat <<'EOF'
## Summary

Promotes the testai frontend through the canonical test overlay before runtime
reconciliation. This PR does **not** call `kubectl set image` or otherwise
mutate the cluster.

- Source commit: `__SOURCE_SHA__`
- Image tag: `__IMAGE_TAG__`
- Immutable image: `__IMAGE__@__IMAGE_DIGEST__`
- Promotion run: __RUN_URL__
- Tracked by: #2295

### Deterministic overlay delta

~~~
__APPLY_OUT__
~~~

After review and merge, `verify-testai-frontend-rollout.yml` reconciles the
merged revision through ArgoCD and verifies the exact pod digest, public module
entry, and `build-info.json` lineage. Authenticated Meeting behavior remains a
separate acceptance gate.

## Boundary declaration (ADR-0011 §2.3)

- [ ] credential-read
- [ ] credential-write
- [x] state-mutation (test cluster)
- [ ] state-mutation (production)
- [ ] boundary-cross
- [ ] user-communication
- [ ] none of the above

The PR changes test desired state only. Runtime mutation occurs later through
ArgoCD after normal review and merge; no production or credential path is used.

## Cross-AI

Automation source: .github/workflows/deploy-testai.yml
Cross-AI exempt reason: Machine-generated immutable frontend desired-state promotion; no AI peer-review claim is made.
Automation evidence: __RUN_URL__

Generated by `scripts/automation/sync-test-overlay-frontend.sh`.
EOF
)
BODY=${BODY//__SOURCE_SHA__/$SHA}
BODY=${BODY//__IMAGE_TAG__/$IMAGE_TAG}
BODY=${BODY//__IMAGE_DIGEST__/$IMAGE_DIGEST}
BODY=${BODY//__IMAGE__/$IMAGE}
BODY=${BODY//__RUN_URL__/$RUN_URL}
BODY=${BODY//__APPLY_OUT__/$APPLY_OUT}

existing=$(gh pr list --repo "$GH_REPO" --head "$BRANCH" --state open \
  --json number --jq '.[0].number // empty')
title="auto(test-overlay): promote frontend ${IMAGE_TAG}"
if [[ -n "$existing" ]]; then
  gh pr edit "$existing" --repo "$GH_REPO" --title "$title" --body "$BODY" >/dev/null
  echo "[frontend-overlay] updated PR #${existing}"
else
  gh pr create --repo "$GH_REPO" --base main --head "$BRANCH" \
    --title "$title" --body "$BODY"
fi
