#!/usr/bin/env bash
set -euo pipefail

# Open or update the desired-state-first frontend promotion PR. This script
# never talks to Kubernetes; ArgoCD reconciliation happens only after review
# and merge through verify-testai-frontend-rollout.yml.

BRANCH="auto-test-frontend/testai"
KUSTOMIZATION="kustomize/overlays/test/kustomization.yaml"
APPLY_SCRIPT="scripts/automation/test-overlay-frontend-image.py"
DIFF_GUARD="scripts/automation/validate-test-overlay-frontend-diff.sh"
GH_REPO="${GITHUB_REPO:-Halildeu/platform-k8s-gitops}"
SERVER_URL="${GITHUB_SERVER_URL:-https://github.com}"
BOT_NAME="platform-gitops-automation[bot]"
BOT_EMAIL="platform-gitops-automation[bot]@users.noreply.github.com"

: "${SHA:?SHA env required}"
: "${SHORT_SHA:?SHORT_SHA env required}"
: "${IMAGE:?IMAGE env required}"
: "${IMAGE_TAG:?IMAGE_TAG env required}"
: "${IMAGE_DIGEST:?IMAGE_DIGEST env required}"
: "${GH_TOKEN:?GH_TOKEN must be a platform-gitops-automation GitHub App token}"

RUN_ID="${RUN_ID:-0}"
RUN_URL="${SERVER_URL}/${GH_REPO}/actions/runs/${RUN_ID}"

git fetch origin main --quiet
git checkout -B "$BRANCH" origin/main --quiet

APPLY_OUT=$(python3 "$APPLY_SCRIPT" apply \
  --kustomization "$KUSTOMIZATION" \
  --sha "$SHA" \
  --short-sha "$SHORT_SHA" \
  --image "$IMAGE" \
  --image-tag "$IMAGE_TAG" \
  --image-digest "$IMAGE_DIGEST")
printf '%s\n' "$APPLY_OUT"

if git diff --quiet -- "$KUSTOMIZATION"; then
  echo "[frontend-overlay] origin/main already contains ${IMAGE_TAG}@${IMAGE_DIGEST}"
  exit 0
fi

bash "$DIFF_GUARD" "$KUSTOMIZATION"

git config user.name "$BOT_NAME"
git config user.email "$BOT_EMAIL"
git add "$KUSTOMIZATION"
git commit --quiet -m "auto(test-overlay): promote frontend ${IMAGE_TAG}

Desired-state-first testai frontend promotion. No direct workload mutation.
Artifact: ${IMAGE}@${IMAGE_DIGEST}
Source: ${SHA}
Run: ${RUN_URL}
Tracked by #2295."
git push --force-with-lease origin "HEAD:${BRANCH}" --quiet

BODY=$(cat <<EOF
## Summary

Promotes the testai frontend through the canonical test overlay before runtime
reconciliation. This PR does **not** call `kubectl set image` or otherwise
mutate the cluster.

- Source commit: `${SHA}`
- Image tag: `${IMAGE_TAG}`
- Immutable image: `${IMAGE}@${IMAGE_DIGEST}`
- Promotion run: ${RUN_URL}
- Tracked by: #2295

### Deterministic overlay delta

~~~
${APPLY_OUT}
~~~

After review and merge, `verify-testai-frontend-rollout.yml` reconciles the
merged revision through ArgoCD and verifies the exact pod digest, public module
entry, and `build-info.json` lineage. Authenticated Meeting behavior remains a
separate acceptance gate.

## Boundary declaration (ADR-0011 §2.3)

- [ ] credential-read
- [ ] credential-write
- [x] state-mutation (test cluster)
- [ ] state-mutation (production)
- [ ] boundary-cross
- [ ] user-communication
- [ ] none of the above

The PR changes test desired state only. Runtime mutation occurs later through
ArgoCD after normal review and merge; no production or credential path is used.

## Cross-AI

Automation source: .github/workflows/deploy-testai.yml
Cross-AI exempt reason: Machine-generated immutable frontend desired-state promotion; no AI peer-review claim is made.
Automation evidence: ${RUN_URL}

Generated by `scripts/automation/sync-test-overlay-frontend.sh`.
EOF
)

existing=$(gh pr list --repo "$GH_REPO" --head "$BRANCH" --state open \
  --json number --jq '.[0].number // empty')
title="auto(test-overlay): promote frontend ${IMAGE_TAG}"
if [[ -n "$existing" ]]; then
  gh pr edit "$existing" --repo "$GH_REPO" --title "$title" --body "$BODY" >/dev/null
  echo "[frontend-overlay] updated PR #${existing}"
else
  gh pr create --repo "$GH_REPO" --base main --head "$BRANCH" \
    --title "$title" --body "$BODY"
fi
