apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/component: ingress
      app.kubernetes.io/part-of: platform
    includeSelectors: false
    includeTemplates: false

resources:
  - ingress.yaml
  - ingress-audio-gateway.yaml
