apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/component: policy
      app.kubernetes.io/part-of: platform
    includeSelectors: false
    includeTemplates: false

resources:
  - quota.yaml
  - limitrange.yaml
