-- Faz 16.2 V16 — generated by scripts/migration/generate_v16_sql.py
-- Codex iter-4 AGREE: 23 matched canonical + 17 parametric placeholder
-- Tables: 40 (matched=20, parametric=17)

BEGIN;

-- 00 EXTENSIONS
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 01 SCHEMAS
CREATE SCHEMA IF NOT EXISTS workcube_mikrolink;
CREATE SCHEMA IF NOT EXISTS workcube_mssql_raw;
CREATE SCHEMA IF NOT EXISTS migration_audit;

-- 02 MIGRATION AUDIT
CREATE TABLE migration_audit.migration_runs (
    id BIGSERIAL PRIMARY KEY,
    run_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('initial','final_delta','reconcile_only','dry_run')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING','SUCCESS','FAILED','ABORTED')),
    source_database VARCHAR(128) NOT NULL,
    worker_version VARCHAR(40),
    git_sha VARCHAR(40),
    contract_version VARCHAR(40),
    annex_version VARCHAR(40),
    started_by VARCHAR(128),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    error_summary TEXT,
    notes JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX idx_migration_runs_status ON migration_audit.migration_runs (status, started_at DESC);

CREATE TABLE migration_audit.migration_table_state (
    run_id UUID NOT NULL REFERENCES migration_audit.migration_runs(run_id) ON DELETE CASCADE,
    table_name VARCHAR(128) NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','EXTRACTING','LOADING','VALIDATED','FAILED')),
    rows_extracted BIGINT NOT NULL DEFAULT 0,
    rows_loaded BIGINT NOT NULL DEFAULT 0,
    rows_rejected BIGINT NOT NULL DEFAULT 0,
    last_pk TEXT,
    checksum VARCHAR(64),
    content_hash VARCHAR(64),
    default_partition_rows BIGINT NOT NULL DEFAULT 0,
    batch_no INTEGER NOT NULL DEFAULT 0,
    extract_query_hash VARCHAR(64),
    max_updated_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

-- PostgreSQL doesn't support expressions in PRIMARY KEY definitions, but it
-- does support expressions in UNIQUE INDEX. The conflict key we actually need
-- is (run_id, table_name, source_schema, COALESCE(source_year, 0)) — i.e.
-- treat NULL year as 0 so canonical and parametric tables share a uniqueness
-- contract. Codex iter-1 flagged this; this UNIQUE INDEX is what
-- preflight_v16_table_state_pk probes at runner startup.
CREATE UNIQUE INDEX idx_migration_table_state_pk
    ON migration_audit.migration_table_state
    (run_id, table_name, source_schema, COALESCE(source_year, 0));

CREATE INDEX idx_migration_table_state_status ON migration_audit.migration_table_state (status, table_name);

CREATE TABLE migration_audit.migration_rejects (
    id BIGSERIAL PRIMARY KEY,
    run_id UUID NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    source_schema VARCHAR(128),
    source_year SMALLINT,
    source_pk TEXT,
    column_name VARCHAR(128),
    reject_reason VARCHAR(40) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'ERROR' CHECK (severity IN ('WARN','ERROR','CRITICAL')),
    source_value TEXT,
    pg_error_code TEXT,
    pg_error_message TEXT,
    raw_payload JSONB,
    rejected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT
);

CREATE INDEX idx_migration_rejects_run ON migration_audit.migration_rejects (run_id, table_name);
CREATE INDEX idx_migration_rejects_unresolved ON migration_audit.migration_rejects (table_name, rejected_at DESC) WHERE resolved_at IS NULL;

-- ===== 03 RAW STAGING + 04+05 FINAL TABLES =====

-- ===== ACCOUNT_CARD (PARAMETRIC — placeholder) =====
-- Used by: fin-kaynak-eslesme, fin-muhasebe-detay, fin-muhasebe-fisleri
-- Schemas: workcube_mikrolink_2026_1, {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.account_card (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_account_card_run ON workcube_mssql_raw.account_card (run_id);

-- workcube_mikrolink.account_card TODO Faz 16.2.P

-- ===== ACCOUNT_CARD_MONEY (PARAMETRIC — placeholder) =====
-- Used by: fin-muhasebe-detay
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.account_card_money (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_account_card_money_run ON workcube_mssql_raw.account_card_money (run_id);

-- workcube_mikrolink.account_card_money TODO Faz 16.2.P

-- ===== ACCOUNT_CARD_ROWS (PARAMETRIC — placeholder) =====
-- Used by: fin-gerceklesen-maliyet, fin-kaynak-eslesme, fin-muhasebe-detay
-- Schemas: workcube_mikrolink_2026_1, {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.account_card_rows (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_account_card_rows_run ON workcube_mssql_raw.account_card_rows (run_id);

-- workcube_mikrolink.account_card_rows TODO Faz 16.2.P

-- ===== ACCOUNT_PLAN (PARAMETRIC — placeholder) =====
-- Used by: fin-muhasebe-detay
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.account_plan (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_account_plan_run ON workcube_mssql_raw.account_plan (run_id);

-- workcube_mikrolink.account_plan TODO Faz 16.2.P

-- ===== BANK_ACTIONS (PARAMETRIC — placeholder) =====
-- Used by: fin-banka-hareketleri, fin-nakit-akis-ozet, fin-tutar-mutabakat
-- Schemas: workcube_mikrolink_1, {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.bank_actions (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_bank_actions_run ON workcube_mssql_raw.bank_actions (run_id);

-- workcube_mikrolink.bank_actions TODO Faz 16.2.P

-- raw staging: BRANCH
CREATE TABLE workcube_mssql_raw.branch (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_branch_run ON workcube_mssql_raw.branch (run_id);

-- BRANCH (canonical, used by: fin-muhasebe-detay, hr-compensation-detay, rowCount=144)
CREATE TABLE workcube_mikrolink.branch (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    branch_status BOOLEAN NOT NULL,
    zone_id INTEGER,
    company_id INTEGER,
    branch_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    admin1_position_code INTEGER,
    admin2_position_code INTEGER,
    branch_name VARCHAR(50) NOT NULL,
    branch_fullname VARCHAR(250),
    branch_email VARCHAR(75),
    branch_telcode VARCHAR(43),
    branch_tel1 VARCHAR(43),
    branch_tel2 VARCHAR(43),
    branch_tel3 VARCHAR(43),
    branch_fax VARCHAR(43),
    branch_address VARCHAR(250),
    branch_postcode VARCHAR(43),
    branch_county VARCHAR(43),
    branch_city VARCHAR(43),
    branch_country VARCHAR(43),
    branch_work VARCHAR(43),
    branch_tax_office VARCHAR(50),
    branch_tax_no VARCHAR(50),
    ssk_office VARCHAR(250),
    ssk_no VARCHAR(50),
    ssk_m VARCHAR(43),
    ssk_job VARCHAR(43),
    ssk_branch VARCHAR(43),
    ssk_branch_old VARCHAR(43),
    map_coordinate VARCHAR(50),
    ssk_city VARCHAR(43),
    ssk_country VARCHAR(43),
    ssk_cd VARCHAR(43),
    ssk_agent VARCHAR(43),
    work_zone_m VARCHAR(43),
    work_zone_job VARCHAR(43),
    work_zone_file VARCHAR(43),
    work_zone_city VARCHAR(43),
    danger_degree INTEGER,
    danger_degree_no DOUBLE PRECISION,
    asset_file_name1 VARCHAR(100),
    asset_file_name1_server_id INTEGER,
    asset_file_name2 VARCHAR(100),
    asset_file_name2_server_id INTEGER,
    foundation_date TIMESTAMPTZ,
    iskur_branch_name VARCHAR(100),
    iskur_branch_no VARCHAR(50),
    cal_bol_mud_name VARCHAR(50),
    real_work VARCHAR(50),
    cal_bol_mud_no VARCHAR(50),
    is_internet BOOLEAN,
    hierarchy VARCHAR(75),
    hierarchy2 VARCHAR(75),
    kanun_5084_oran INTEGER,
    is_sakat_kontrol BOOLEAN,
    related_company VARCHAR(150),
    related_branch_id INTEGER,
    ozel_kod VARCHAR(50),
    is_organization BOOLEAN,
    related_company_branch_id INTEGER,
    open_date TIMESTAMPTZ,
    tckimlik_no VARCHAR(43),
    user_name VARCHAR(43),
    system_password VARCHAR(60),
    company_password VARCHAR(60),
    ssk_employee_id INTEGER,
    ssk_position_code INTEGER,
    employee_system_name VARCHAR(100),
    position_name VARCHAR(100),
    branch_pdks_code VARCHAR(200),
    is_5510 BOOLEAN,
    is_5615 BOOLEAN,
    branch_pdks_ip_numbers VARCHAR(500),
    is_production BOOLEAN,
    is_pdks_work BOOLEAN,
    branch_cat_id INTEGER,
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    is_5615_tax_off BOOLEAN,
    iskur_password VARCHAR(50),
    iskur_tckimlik_no VARCHAR(50),
    coordinate_1 VARCHAR(50),
    coordinate_2 VARCHAR(50),
    kanun_6486 INTEGER,
    kanun_6322 INTEGER,
    wex_address VARCHAR(500),
    detail VARCHAR(250),
    file_no INTEGER,
    expense_alpha VARCHAR(43),
    expense_unit_code5 VARCHAR(43),
    acc_comp_name VARCHAR(100),
    acc_unit_code VARCHAR(43),
    expense_tc VARCHAR(43),
    expense_unit_code1 VARCHAR(43),
    expense_user_name VARCHAR(43),
    expense_unit_code2 VARCHAR(43),
    expense_unit_code3 VARCHAR(43),
    expense_unit_code4 VARCHAR(43),
    salary_syndic_pos_id INTEGER,
    fulfillment_officer_pos_id INTEGER,
    expense_user_pos_id INTEGER,
    kanun_5746_information TEXT,
    branch_project_code VARCHAR(200),
    rate_5510 INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_branch_hash ON workcube_mikrolink.branch (content_hash);
CREATE INDEX idx_branch_lineage ON workcube_mikrolink.branch (source_schema, source_table, source_pk);

-- ===== BUDGET_PLAN_ROW (PARAMETRIC — placeholder) =====
-- Used by: fin-butce-gerceklesen
-- Schemas: workcube_mikrolink
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.budget_plan_row (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_budget_plan_row_run ON workcube_mssql_raw.budget_plan_row (run_id);

-- workcube_mikrolink.budget_plan_row TODO Faz 16.2.P

-- ===== CARI_ACTIONS (PARAMETRIC — placeholder) =====
-- Used by: fin-cari-islemler, fin-tutar-mutabakat
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.cari_actions (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_cari_actions_run ON workcube_mssql_raw.cari_actions (run_id);

-- workcube_mikrolink.cari_actions TODO Faz 16.2.P

-- ===== CARI_ROWS (PARAMETRIC — placeholder) =====
-- Used by: fin-cari-hareketler, fin-cari-mutabakat
-- Schemas: workcube_mikrolink_1
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.cari_rows (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_cari_rows_run ON workcube_mssql_raw.cari_rows (run_id);

-- workcube_mikrolink.cari_rows TODO Faz 16.2.P

-- ===== CASH_ACTIONS (PARAMETRIC — placeholder) =====
-- Used by: fin-kasa-hareketleri
-- Schemas: workcube_mikrolink_1
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.cash_actions (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_cash_actions_run ON workcube_mssql_raw.cash_actions (run_id);

-- workcube_mikrolink.cash_actions TODO Faz 16.2.P

-- ===== CHEQUE (PARAMETRIC — placeholder) =====
-- Used by: fin-cek-senet, fin-cek-vade-takip
-- Schemas: workcube_mikrolink_1
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.cheque (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_cheque_run ON workcube_mssql_raw.cheque (run_id);

-- workcube_mikrolink.cheque TODO Faz 16.2.P

-- raw staging: COMPANY
CREATE TABLE workcube_mssql_raw.company (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_company_run ON workcube_mssql_raw.company (run_id);

-- COMPANY (canonical, used by: fin-cari-islemler, fin-fatura-satirlari, fin-kaynak-eslesme, rowCount=80207)
CREATE TABLE workcube_mikrolink.company (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    company_status BOOLEAN NOT NULL,
    companycat_id INTEGER NOT NULL,
    company_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    our_company_id INTEGER,
    member_code VARCHAR(50),
    partner_id INTEGER,
    discount INTEGER,
    pos_code INTEGER,
    manager_partner_id INTEGER,
    nickname VARCHAR(150),
    fullname VARCHAR(250),
    sector_cat_id INTEGER,
    company_size_cat_id INTEGER,
    company_value_id INTEGER,
    taxoffice VARCHAR(50),
    taxno VARCHAR(43),
    company_email VARCHAR(100),
    homepage VARCHAR(50),
    company_telcode VARCHAR(43),
    company_tel1 VARCHAR(43),
    company_tel2 VARCHAR(43),
    company_tel3 VARCHAR(43),
    company_fax VARCHAR(43),
    mobil_code VARCHAR(43),
    mobiltel VARCHAR(43),
    company_postcode VARCHAR(43),
    company_address VARCHAR(200),
    dukkan_no VARCHAR(50),
    main_street VARCHAR(50),
    street VARCHAR(50),
    district_id INTEGER,
    semt VARCHAR(50),
    county INTEGER,
    city INTEGER,
    country INTEGER,
    resource_id INTEGER,
    ispotantial BOOLEAN,
    hierarchy_id INTEGER,
    sales_county INTEGER,
    is_buyer BOOLEAN,
    is_seller BOOLEAN,
    period_id INTEGER,
    company_rate DOUBLE PRECISION,
    risk_limit DOUBLE PRECISION,
    start_date TIMESTAMPTZ,
    org_start_date TIMESTAMPTZ,
    ozel_kod VARCHAR(75),
    ozel_kod_1 VARCHAR(75),
    ozel_kod_2 VARCHAR(75),
    ims_code_id INTEGER,
    company_state INTEGER,
    company_fax_code VARCHAR(43),
    con_close_date TIMESTAMPTZ,
    con_open_date TIMESTAMPTZ,
    old_company_id INTEGER,
    district VARCHAR(50),
    duty_period INTEGER,
    email VARCHAR(50),
    endorse_currency VARCHAR(43),
    endorse_payment DOUBLE PRECISION,
    endorse_period INTEGER,
    stock_amount INTEGER,
    ref_no VARCHAR(50),
    money_currency VARCHAR(43),
    grup_risk_limit DOUBLE PRECISION,
    guess_endorsement_money VARCHAR(43),
    guess_endorsement DOUBLE PRECISION,
    is_related_company BOOLEAN,
    company_work_type INTEGER,
    asset_file_name1 VARCHAR(150),
    asset_file_name1_server_id INTEGER,
    asset_file_name2 VARCHAR(150),
    asset_file_name2_server_id INTEGER,
    ekstre BOOLEAN,
    member_add_option_id INTEGER,
    wrk_id VARCHAR(43),
    glncode VARCHAR(43),
    record_par INTEGER,
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    update_par INTEGER,
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    coordinate_1 VARCHAR(50),
    coordinate_2 VARCHAR(50),
    campaign_id INTEGER,
    _multiple_sector_cat_id VARCHAR(250),
    firm_type VARCHAR(250),
    domestic_value_id INTEGER,
    export_value_id INTEGER,
    company_detail VARCHAR(1500),
    sort INTEGER,
    is_homepage BOOLEAN,
    company_detail_eng VARCHAR(1500),
    company_detail_spa VARCHAR(1500),
    is_export BOOLEAN,
    visit_cat_id INTEGER,
    use_efatura BOOLEAN,
    efatura_date TIMESTAMPTZ,
    profile_id VARCHAR(50),
    is_person BOOLEAN,
    use_earchive BOOLEAN,
    earchive_sending_type BOOLEAN,
    company_kep_address VARCHAR(250),
    is_civil_company BOOLEAN,
    domain VARCHAR(100),
    watalogy_member_code VARCHAR(50),
    use_eshipment BOOLEAN,
    eshipment_alias VARCHAR(100),
    payment_group_id INTEGER,
    genius_id INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_company_hash ON workcube_mikrolink.company (content_hash);
CREATE INDEX idx_company_lineage ON workcube_mikrolink.company (source_schema, source_table, source_pk);

-- ===== COMPANY_REMAINDER (PARAMETRIC — placeholder) =====
-- Used by: fin-alacak-yaslandirma, fin-borc-yaslandirma
-- Schemas: workcube_mikrolink_1
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.company_remainder (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_company_remainder_run ON workcube_mssql_raw.company_remainder (run_id);

-- workcube_mikrolink.company_remainder TODO Faz 16.2.P

-- raw staging: CONSUMER
CREATE TABLE workcube_mssql_raw.consumer (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_consumer_run ON workcube_mssql_raw.consumer (run_id);

-- CONSUMER (canonical, used by: fin-muhasebe-detay, rowCount=55276)
CREATE TABLE workcube_mikrolink.consumer (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    consumer_status BOOLEAN NOT NULL,
    consumer_cat_id INTEGER NOT NULL,
    consumer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_code VARCHAR(50),
    consumer_username VARCHAR(50),
    consumer_password VARCHAR(300),
    level_id INTEGER,
    design_id INTEGER,
    language_id VARCHAR(43),
    timeout_limit INTEGER,
    consumer_name VARCHAR(100),
    consumer_surname VARCHAR(100),
    consumer_email VARCHAR(100),
    imcat_id INTEGER,
    im VARCHAR(43),
    consumer_worktelcode VARCHAR(43),
    consumer_worktel VARCHAR(43),
    consumer_tel_ext VARCHAR(43),
    mobil_code VARCHAR(43),
    mobiltel VARCHAR(43),
    mobil_code_2 VARCHAR(43),
    mobiltel_2 VARCHAR(50),
    consumer_faxcode VARCHAR(43),
    consumer_fax VARCHAR(43),
    consumer_hometelcode VARCHAR(43),
    consumer_hometel VARCHAR(43),
    birthdate TIMESTAMPTZ,
    birthplace VARCHAR(43),
    company VARCHAR(100),
    sector_cat_id INTEGER,
    company_size_cat_id INTEGER,
    consumer_stage INTEGER,
    education VARCHAR(40),
    education_id INTEGER,
    sex BOOLEAN,
    picture VARCHAR(100),
    picture_server_id INTEGER,
    identycard_cat VARCHAR(40),
    identycard_no VARCHAR(40),
    married BOOLEAN,
    married_date TIMESTAMPTZ,
    child VARCHAR(43),
    homeaddress VARCHAR(750),
    homepostcode VARCHAR(43),
    homesemt VARCHAR(150),
    home_county_id INTEGER,
    home_city_id INTEGER,
    home_country_id INTEGER,
    home_district VARCHAR(250),
    home_district_id INTEGER,
    home_main_street VARCHAR(250),
    home_street VARCHAR(250),
    home_door_no VARCHAR(250),
    workaddress VARCHAR(750),
    workpostcode VARCHAR(43),
    worksemt VARCHAR(43),
    work_county_id INTEGER,
    work_city_id INTEGER,
    work_country_id INTEGER,
    work_district VARCHAR(250),
    work_district_id INTEGER,
    work_main_street VARCHAR(250),
    work_street VARCHAR(250),
    work_door_no VARCHAR(250),
    tax_office VARCHAR(250),
    tax_no VARCHAR(250),
    tax_adress VARCHAR(750),
    tax_postcode VARCHAR(43),
    tax_semt VARCHAR(150),
    tax_county_id INTEGER,
    tax_city_id INTEGER,
    tax_country_id INTEGER,
    tax_district VARCHAR(250),
    tax_district_id INTEGER,
    tax_main_street VARCHAR(250),
    tax_street VARCHAR(250),
    tax_door_no VARCHAR(250),
    homepage VARCHAR(50),
    member_type INTEGER,
    ispotantial BOOLEAN,
    is_cari BOOLEAN,
    _consumer_card_no VARCHAR(50),
    sales_county INTEGER,
    ref_pos_code INTEGER,
    hierarchy_id INTEGER,
    period_id INTEGER,
    title VARCHAR(50),
    mission INTEGER,
    department INTEGER,
    ozel_kod VARCHAR(50),
    tc_identy_no VARCHAR(50),
    social_society_id INTEGER,
    social_security_no VARCHAR(50),
    father VARCHAR(50),
    mother VARCHAR(50),
    ilgi INTEGER,
    ilgino VARCHAR(100),
    yas INTEGER,
    arsiv_no1 VARCHAR(100),
    arsiv_no2 VARCHAR(100),
    want_email BOOLEAN,
    member_rules BOOLEAN,
    ims_code_id INTEGER,
    mail_id INTEGER,
    income_level_id INTEGER,
    vocation_type_id INTEGER,
    nationality INTEGER,
    resource_id INTEGER,
    customer_value_id INTEGER,
    start_date TIMESTAMPTZ,
    is_related_consumer BOOLEAN,
    blood_type INTEGER,
    _is_mycube_member BOOLEAN,
    consumer_reference_code VARCHAR(500),
    add_flag BOOLEAN,
    terminate_date TIMESTAMPTZ,
    ref_change_date TIMESTAMPTZ,
    ref_change_camp_id INTEGER,
    is_taxpayer BOOLEAN,
    proposer_cons_id INTEGER,
    tax_address_type INTEGER,
    last_password_change TIMESTAMPTZ,
    member_add_option_id INTEGER,
    wrk_id VARCHAR(43),
    transfer_date TIMESTAMPTZ,
    transfer_ims_code_id INTEGER,
    record_date TIMESTAMPTZ,
    record_member INTEGER,
    record_par INTEGER,
    record_cons INTEGER,
    record_ip VARCHAR(50),
    update_cons INTEGER,
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    campaign_id INTEGER,
    is_delete BOOLEAN,
    coordinate_1 VARCHAR(50),
    coordinate_2 VARCHAR(50),
    want_sms BOOLEAN,
    contract_date TIMESTAMPTZ,
    contract_cons_id INTEGER,
    contract_emp_id INTEGER,
    contract_date2 TIMESTAMPTZ,
    contract_cons_id2 INTEGER,
    contract_cons_emp2 INTEGER,
    efatura_date TIMESTAMPTZ,
    use_efatura BOOLEAN,
    profile_id VARCHAR(50),
    use_earchive BOOLEAN,
    earchive_sending_type BOOLEAN,
    consumer_kep_address VARCHAR(250),
    use_eshipment BOOLEAN,
    eshipment_alias VARCHAR(100),
    genius_id INTEGER,
    want_call BOOLEAN,
    twinhub_url VARCHAR(250),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_consumer_hash ON workcube_mikrolink.consumer (content_hash);
CREATE INDEX idx_consumer_lineage ON workcube_mikrolink.consumer (source_schema, source_table, source_pk);

-- raw staging: DEPARTMENT
CREATE TABLE workcube_mssql_raw.department (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_department_run ON workcube_mssql_raw.department (run_id);

-- DEPARTMENT (canonical, used by: fin-muhasebe-detay, rowCount=1214)
CREATE TABLE workcube_mikrolink.department (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    department_status BOOLEAN,
    is_production BOOLEAN,
    is_store INTEGER,
    branch_id INTEGER,
    department_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_head VARCHAR(100) NOT NULL,
    department_detail VARCHAR(150),
    admin1_position_code INTEGER,
    admin2_position_code INTEGER,
    hierarchy_dep_id VARCHAR(50),
    hierarchy VARCHAR(75),
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    is_organization BOOLEAN,
    headquarters_id INTEGER,
    our_company_id INTEGER,
    zone_id INTEGER,
    x_coordinate VARCHAR(50),
    y_coordinate VARCHAR(50),
    z_coordinate VARCHAR(50),
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    department_email VARCHAR(50),
    level_no INTEGER,
    change_date TIMESTAMPTZ,
    in_company_reason_id INTEGER,
    _department_name_id INTEGER,
    dept_stage INTEGER,
    special_code VARCHAR(50),
    point_multiplier DOUBLE PRECISION,
    department_cat INTEGER,
    special_code2 VARCHAR(100),
    department_type INTEGER,
    department_tel VARCHAR(50),
    department_address VARCHAR(500),
    department_country_id INTEGER,
    department_city_id INTEGER,
    department_county_id INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_department_hash ON workcube_mikrolink.department (content_hash);
CREATE INDEX idx_department_lineage ON workcube_mikrolink.department (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES
CREATE TABLE workcube_mssql_raw.employees (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_run ON workcube_mssql_raw.employees (run_id);

-- EMPLOYEES (canonical, used by: fin-muhasebe-detay, hr-compensation-detay, rowCount=11710)
CREATE TABLE workcube_mikrolink.employees (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    employee_status BOOLEAN NOT NULL,
    employee_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    empapp_id INTEGER,
    member_code VARCHAR(50),
    employee_username VARCHAR(50),
    employee_password VARCHAR(300),
    employee_no VARCHAR(50),
    employee_name VARCHAR(50) NOT NULL,
    employee_surname VARCHAR(50),
    task VARCHAR(50),
    employee_email VARCHAR(50),
    imcat_id INTEGER,
    im VARCHAR(50),
    imcat2_id INTEGER,
    im2 VARCHAR(50),
    direct_telcode VARCHAR(43),
    direct_tel VARCHAR(43),
    extension VARCHAR(43),
    mobilcode VARCHAR(43),
    mobiltel VARCHAR(43),
    corbus_tel VARCHAR(43),
    photo VARCHAR(500),
    is_agenda_open BOOLEAN,
    period_id INTEGER,
    company_id INTEGER,
    is_ip_control BOOLEAN,
    ip_address VARCHAR(50),
    computer_name VARCHAR(50),
    group_startdate TIMESTAMPTZ,
    dynamic_hierarchy VARCHAR(200),
    dynamic_hierarchy_add VARCHAR(50),
    hierarchy VARCHAR(50),
    ozel_kod VARCHAR(50),
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    ozel_kod2 VARCHAR(50),
    kidem_date TIMESTAMPTZ,
    izin_date TIMESTAMPTZ,
    in_company_reason_id INTEGER,
    is_critical BOOLEAN,
    photo_server_id INTEGER,
    expiry_date TIMESTAMPTZ,
    employee_stage INTEGER,
    biography VARCHAR(1000),
    wet_signature TEXT,
    per_assign_id INTEGER,
    is_acc_info BOOLEAN,
    izin_days DOUBLE PRECISION,
    old_sgk_days INTEGER,
    ext_offtime_minutes INTEGER,
    ext_offtime_date TIMESTAMPTZ,
    __imcat_id INTEGER,
    __im VARCHAR(50),
    __im2 VARCHAR(50),
    __imcat2_id INTEGER,
    worktips_open BOOLEAN,
    tel_type INTEGER,
    employee_kep_adress VARCHAR(200),
    eins_point DOUBLE PRECISION,
    bruc_point DOUBLE PRECISION,
    is_vaccine BOOLEAN,
    is_covid BOOLEAN,
    mfa_secret VARCHAR(250),
    mfa_type INTEGER,
    project_id INTEGER,
    office365_mail_status BOOLEAN,
    office365_mail_licence BOOLEAN,
    is_interruption BOOLEAN,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_hash ON workcube_mikrolink.employees (content_hash);
CREATE INDEX idx_employees_lineage ON workcube_mikrolink.employees (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_DETAIL
CREATE TABLE workcube_mssql_raw.employees_detail (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_detail_run ON workcube_mssql_raw.employees_detail (run_id);

-- EMPLOYEES_DETAIL (canonical, used by: hr-compensation-detay, rowCount=11708)
CREATE TABLE workcube_mikrolink.employees_detail (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    employee_id INTEGER NOT NULL,
    employee_detail_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    calculate_formul INTEGER,
    defected BOOLEAN,
    defected_level INTEGER,
    defected_probability BOOLEAN,
    illness_probability BOOLEAN,
    illness_detail TEXT,
    identycard_cat INTEGER,
    identycard_no VARCHAR(50),
    sex BOOLEAN,
    child_0 INTEGER,
    child_1 INTEGER,
    child_2 INTEGER,
    child_3 INTEGER,
    partner_company VARCHAR(40),
    partner_position VARCHAR(40),
    hometel_code VARCHAR(43),
    hometel VARCHAR(43),
    homeaddress VARCHAR(500),
    homepostcode VARCHAR(43),
    homecity INTEGER,
    homecountry INTEGER,
    contact1 VARCHAR(40),
    contact1_relation VARCHAR(40),
    contact1_email VARCHAR(50),
    contact1_telcode VARCHAR(43),
    contact1_tel VARCHAR(43),
    contact2 VARCHAR(40),
    contact2_relation VARCHAR(40),
    contact2_email VARCHAR(50),
    contact2_telcode VARCHAR(43),
    contact2_tel VARCHAR(43),
    tools VARCHAR(1000),
    military_status INTEGER,
    military_delay_reason VARCHAR(43),
    military_delay_date TIMESTAMPTZ,
    startdate TIMESTAMPTZ,
    finishdate TIMESTAMPTZ,
    shift_id INTEGER,
    is_foreigner BOOLEAN,
    kurs1 VARCHAR(150),
    kurs2 VARCHAR(150),
    kurs3 VARCHAR(150),
    sentenced BOOLEAN,
    sentenced_six_month BOOLEAN,
    last_school INTEGER,
    terror_wronged BOOLEAN,
    suit_probability BOOLEAN,
    suit_detail TEXT,
    test_time INTEGER,
    test_detail TEXT,
    caution_time INTEGER,
    caution_emp INTEGER,
    quiz_id INTEGER,
    new_company VARCHAR(100),
    new_company_pos VARCHAR(100),
    record_emp INTEGER,
    update_emp INTEGER,
    record_ip VARCHAR(50),
    update_ip VARCHAR(50),
    record_date TIMESTAMPTZ,
    update_date TIMESTAMPTZ,
    military_finishdate TIMESTAMPTZ,
    military_month INTEGER,
    military_exempt_detail VARCHAR(100),
    use_cigarette BOOLEAN,
    martyr_relative BOOLEAN,
    military_rank BOOLEAN,
    kurs1_yil TIMESTAMPTZ,
    kurs1_yer VARCHAR(150),
    kurs1_gun VARCHAR(50),
    kurs2_yil TIMESTAMPTZ,
    kurs2_yer VARCHAR(150),
    kurs2_gun VARCHAR(50),
    kurs3_yil TIMESTAMPTZ,
    kurs3_yer VARCHAR(150),
    kurs3_gun VARCHAR(50),
    edu4_diploma_no VARCHAR(50),
    comp_exp TEXT,
    club VARCHAR(300),
    homecounty INTEGER,
    email_spc VARCHAR(100),
    direct_telcode_spc VARCHAR(43),
    direct_tel_spc VARCHAR(43),
    extension_spc VARCHAR(43),
    mobilcode_spc VARCHAR(43),
    mobiltel_spc VARCHAR(43),
    mobilcode2_spc VARCHAR(43),
    mobiltel2_spc VARCHAR(43),
    neighborhood VARCHAR(100),
    boulevard VARCHAR(100),
    avenue VARCHAR(100),
    street VARCHAR(100),
    external_door_number VARCHAR(43),
    internal_door_number VARCHAR(43),
    neighborhood1 VARCHAR(100),
    _lang2_level INTEGER,
    _ref1_emp VARCHAR(40),
    _ref2_company VARCHAR(40),
    _lang2_mean INTEGER,
    _lang1_where VARCHAR(50),
    _lang4_write INTEGER,
    _ref2_emp VARCHAR(40),
    _ref2_email VARCHAR(50),
    _ref1 VARCHAR(40),
    _lang1_speak INTEGER,
    _lang4_where VARCHAR(50),
    _ref2 VARCHAR(40),
    _lang4_speak INTEGER,
    _ref1_company_emp VARCHAR(40),
    _ref2_telcode_emp VARCHAR(43),
    _lang1_write INTEGER,
    _lang5_where VARCHAR(50),
    _ref1_telcode VARCHAR(43),
    _lang1_level INTEGER,
    _ref2_company_emp VARCHAR(40),
    _ref1_tel_emp VARCHAR(43),
    _ref2_email_emp VARCHAR(40),
    _lang5_write INTEGER,
    _ref2_position_emp VARCHAR(40),
    _lang3_mean INTEGER,
    _lang5_level INTEGER,
    _ref1_email VARCHAR(50),
    _ref1_position_emp VARCHAR(40),
    _ref1_telcode_emp VARCHAR(43),
    _ref1_company VARCHAR(40),
    _lang2_where VARCHAR(50),
    _ref2_tel VARCHAR(43),
    _lang3_speak INTEGER,
    _lang2_write INTEGER,
    _lang5_mean INTEGER,
    _ref1_email_emp VARCHAR(40),
    _lang4_level INTEGER,
    _ref1_tel VARCHAR(43),
    _lang1_mean INTEGER,
    _lang4_mean INTEGER,
    _lang5 INTEGER,
    _ref2_telcode VARCHAR(43),
    _lang3_where VARCHAR(50),
    _lang3_level INTEGER,
    _lang3_write INTEGER,
    _lang3 INTEGER,
    _ref2_position VARCHAR(40),
    _lang4 INTEGER,
    _lang1 INTEGER,
    _lang2 INTEGER,
    _ref2_tel_emp VARCHAR(43),
    _lang2_speak INTEGER,
    _ref1_position VARCHAR(40),
    _lang5_speak INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_detail_hash ON workcube_mikrolink.employees_detail (content_hash);
CREATE INDEX idx_employees_detail_lineage ON workcube_mikrolink.employees_detail (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_IDENTY
CREATE TABLE workcube_mssql_raw.employees_identy (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_identy_run ON workcube_mssql_raw.employees_identy (run_id);

-- EMPLOYEES_IDENTY (canonical, used by: hr-compensation-detay, rowCount=14291)
CREATE TABLE workcube_mikrolink.employees_identy (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    empapp_id INTEGER,
    employee_id INTEGER,
    employee_identy_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tc_identy_no VARCHAR(50),
    tax_number VARCHAR(50),
    tax_office VARCHAR(50),
    series VARCHAR(43),
    number VARCHAR(50),
    father VARCHAR(75),
    father_job VARCHAR(50),
    mother VARCHAR(75),
    mother_job VARCHAR(50),
    birth_date TIMESTAMPTZ,
    birth_place VARCHAR(100),
    married BOOLEAN,
    religion VARCHAR(50),
    blood_type INTEGER,
    city VARCHAR(100),
    county VARCHAR(100),
    ward VARCHAR(100),
    village VARCHAR(100),
    binding VARCHAR(43),
    family VARCHAR(43),
    cue VARCHAR(43),
    given_place VARCHAR(100),
    given_reason VARCHAR(300),
    record_number VARCHAR(50),
    given_date TIMESTAMPTZ,
    last_surname VARCHAR(100),
    record_date TIMESTAMPTZ,
    record_ip VARCHAR(50),
    record_emp INTEGER,
    update_date TIMESTAMPTZ,
    update_ip VARCHAR(50),
    update_emp INTEGER,
    nationality INTEGER,
    socialsecurity_no VARCHAR(50),
    birth_city INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_identy_hash ON workcube_mikrolink.employees_identy (content_hash);
CREATE INDEX idx_employees_identy_lineage ON workcube_mikrolink.employees_identy (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_IN_OUT
CREATE TABLE workcube_mssql_raw.employees_in_out (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_in_out_run ON workcube_mssql_raw.employees_in_out (run_id);

-- EMPLOYEES_IN_OUT (canonical, used by: hr-compensation-detay, hr-giris-cikis, rowCount=12924)
CREATE TABLE workcube_mikrolink.employees_in_out (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    in_out_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    branch_id INTEGER,
    department_id INTEGER,
    business_code_id INTEGER,
    employee_id INTEGER NOT NULL,
    start_date TIMESTAMPTZ NOT NULL,
    finish_date TIMESTAMPTZ,
    ihbar_date TIMESTAMPTZ,
    validator_position_code INTEGER,
    valid_emp INTEGER,
    valid_date TIMESTAMPTZ,
    valid BOOLEAN,
    detail VARCHAR(300),
    salary DOUBLE PRECISION,
    ihbar_days INTEGER,
    ihbar_amount DOUBLE PRECISION,
    kidem_years INTEGER,
    kidem_amount DOUBLE PRECISION,
    total_deneme_days INTEGER,
    total_ssk_days INTEGER,
    total_ssk_months INTEGER,
    hakedilen_yillik_izin INTEGER,
    kullanilmayan_izin_count DOUBLE PRECISION,
    kullanilmayan_izin_amount DOUBLE PRECISION,
    explanation_id INTEGER,
    is_5084 BOOLEAN,
    record_date TIMESTAMPTZ NOT NULL,
    record_ip VARCHAR(50),
    record_emp INTEGER NOT NULL,
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    in_company_reason_id INTEGER,
    socialsecurity_no VARCHAR(50),
    duty_type INTEGER,
    effected_corporate_change BOOLEAN,
    paymethod_id INTEGER,
    allocation_deduction DOUBLE PRECISION,
    allocation_deduction_money VARCHAR(43),
    gross_net BOOLEAN,
    salary_type INTEGER,
    sabit_prim BOOLEAN,
    salary1 DOUBLE PRECISION,
    money VARCHAR(43),
    cumulative_tax_total DOUBLE PRECISION,
    retired_sgdp_number VARCHAR(50),
    use_ssk INTEGER,
    use_tax BOOLEAN,
    trade_union VARCHAR(200),
    trade_union_no VARCHAR(50),
    trade_union_deduction DOUBLE PRECISION,
    trade_union_deduction_money VARCHAR(43),
    ssk_statute INTEGER,
    defection_level INTEGER,
    salary_visible BOOLEAN,
    first_ssk_date TIMESTAMPTZ,
    old_company_start_date TIMESTAMPTZ,
    start_cumulative_tax DOUBLE PRECISION,
    sureli_is_akdi BOOLEAN,
    sureli_is_finishdate TIMESTAMPTZ,
    is_vardiya INTEGER,
    pdks_number VARCHAR(100),
    is_ssk_isveren BOOLEAN,
    ozel_gider_indirim DOUBLE PRECISION,
    ozel_gider_vergi DOUBLE PRECISION,
    mahsup_iade DOUBLE PRECISION,
    fazla_mesai_saat INTEGER,
    fis_toplam DOUBLE PRECISION,
    is_sakat_kontrol BOOLEAN,
    position_code INTEGER,
    is_tax_free BOOLEAN,
    shift_id INTEGER,
    is_discount_off BOOLEAN,
    is_use_506 BOOLEAN,
    is_puantaj_off BOOLEAN,
    days_506 INTEGER,
    doc_repeat BOOLEAN,
    is_5510 BOOLEAN,
    is_start_cumulative_tax BOOLEAN,
    gross_count_type INTEGER,
    is_empty_position BOOLEAN,
    law_numbers VARCHAR(250),
    pdks_type_id INTEGER,
    transport_type_id INTEGER,
    is_kismi_istihdam BOOLEAN,
    kismi_istihdam_gun INTEGER,
    kismi_istihdam_hs_gun INTEGER,
    is_damga_free BOOLEAN,
    date_5763 TIMESTAMPTZ,
    kismi_istihdam_gt_gun INTEGER,
    days_5746 INTEGER,
    use_pdks INTEGER,
    duty_type_company_id INTEGER,
    entry_date TIMESTAMPTZ,
    entry_branch_id INTEGER,
    entry_department_id INTEGER,
    is_salary_transfer BOOLEAN,
    is_salary_detail_transfer BOOLEAN,
    is_accounting_transfer BOOLEAN,
    ex_in_out_id INTEGER,
    is_update_position BOOLEAN,
    date_6111 TIMESTAMPTZ,
    date_6111_select INTEGER,
    puantaj_group_ids VARCHAR(250),
    is_6486 BOOLEAN,
    is_6322 BOOLEAN,
    kismi_istihdam_saat DOUBLE PRECISION,
    is_kidem_baz BOOLEAN,
    is_25510 BOOLEAN,
    is_14857 BOOLEAN,
    warning_emp_id INTEGER,
    in_out_stage INTEGER,
    new_card_account_bill_type INTEGER,
    days_4691 INTEGER,
    is_kidem_ihbar_all_total BOOLEAN,
    working_abroad BOOLEAN,
    is_6645 BOOLEAN,
    start_mon_6645 INTEGER,
    start_year_6645 INTEGER,
    end_mon_6645 INTEGER,
    end_year_6645 INTEGER,
    is_46486 BOOLEAN,
    is_56486 BOOLEAN,
    is_66486 BOOLEAN,
    is_tax_free_687 INTEGER,
    benefit_month_7103 INTEGER,
    defection_rate INTEGER,
    is_status_employee BOOLEAN,
    _is_ihbar_hesap BOOLEAN,
    _is_flight_ticket BOOLEAN,
    _is_kidem_hesap BOOLEAN,
    _out_stage INTEGER,
    _project_id INTEGER,
    _is_store BOOLEAN,
    benefit_day_7252 INTEGER,
    startdate_7256 TIMESTAMPTZ,
    finishdate_7256 TIMESTAMPTZ,
    monthly_average_net DOUBLE PRECISION,
    is_education_allowance INTEGER,
    step_normal INTEGER,
    is_audit_compensation BOOLEAN,
    suspension_finishdate TIMESTAMPTZ,
    financial_responsibility DOUBLE PRECISION,
    severance_pension_score DOUBLE PRECISION,
    is_penance_deduction BOOLEAN,
    defection_finishdate TIMESTAMPTZ,
    administrative_academic INTEGER,
    business_risk_emp DOUBLE PRECISION,
    is_veteran BOOLEAN,
    jul_difficulties DOUBLE PRECISION,
    is_suspension BOOLEAN,
    work_difficulty DOUBLE PRECISION,
    defection_startdate TIMESTAMPTZ,
    additional_indicator_compensation DOUBLE PRECISION,
    additional_score_normal DOUBLE PRECISION,
    audit_compensation DOUBLE PRECISION,
    grade_normal INTEGER,
    suspension_startdate TIMESTAMPTZ,
    language_allowance_1 INTEGER,
    executive_indicator_score DOUBLE PRECISION,
    university_allowance DOUBLE PRECISION,
    language_allowance_5 INTEGER,
    language_allowance_4 INTEGER,
    director_share DOUBLE PRECISION,
    language_allowance_3 INTEGER,
    language_allowance_2 INTEGER,
    academic_incentive_allowance DOUBLE PRECISION,
    startdate_shift TIMESTAMPTZ,
    finishdate_shift TIMESTAMPTZ,
    minimum_course_hours INTEGER,
    administrative_indicator_score DOUBLE PRECISION,
    high_education_compensation DOUBLE PRECISION,
    additional_score DOUBLE PRECISION,
    step INTEGER,
    private_service_score DOUBLE PRECISION,
    additional_course_position INTEGER,
    language_id_5 INTEGER,
    employee_share INTEGER,
    grade INTEGER,
    language_id_1 INTEGER,
    language_id_2 INTEGER,
    language_id_3 INTEGER,
    administrative_function_allowance DOUBLE PRECISION,
    language_id_4 INTEGER,
    perquisite_score DOUBLE PRECISION,
    registry_no VARCHAR(150),
    retired_registry_no VARCHAR(150),
    land_compensation_score DOUBLE PRECISION,
    land_compensation_period INTEGER,
    service_class INTEGER,
    service_title INTEGER,
    jury_membership BOOLEAN,
    past_agi_day DOUBLE PRECISION,
    jury_membership_period INTEGER,
    jury_number INTEGER,
    use_minimum_wage BOOLEAN,
    start_cumulative_wage DOUBLE PRECISION,
    start_cumulative_wage_total DOUBLE PRECISION,
    is_retired_5510 INTEGER,
    is_no_5510 BOOLEAN,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_in_out_hash ON workcube_mikrolink.employees_in_out (content_hash);
CREATE INDEX idx_employees_in_out_lineage ON workcube_mikrolink.employees_in_out (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_PUANTAJ
CREATE TABLE workcube_mssql_raw.employees_puantaj (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_puantaj_run ON workcube_mssql_raw.employees_puantaj (run_id);

-- EMPLOYEES_PUANTAJ (canonical, used by: hr-compensation-detay, rowCount=3390)
CREATE TABLE workcube_mikrolink.employees_puantaj (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    puantaj_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sal_mon INTEGER NOT NULL,
    sal_year INTEGER NOT NULL,
    is_account BOOLEAN,
    is_locked BOOLEAN,
    ssk_office VARCHAR(250),
    ssk_office_no VARCHAR(50) NOT NULL,
    record_date TIMESTAMPTZ NOT NULL,
    record_ip VARCHAR(50),
    record_emp INTEGER NOT NULL,
    mail_date TIMESTAMPTZ,
    comp_nick_name VARCHAR(50),
    comp_full_name VARCHAR(200),
    puantaj_branch_name VARCHAR(50),
    puantaj_branch_full_name VARCHAR(250),
    is_budget BOOLEAN,
    ssk_branch_id INTEGER,
    puantaj_type INTEGER,
    hierarchy VARCHAR(50),
    stage_row_id INTEGER,
    is_lock_control BOOLEAN,
    payment_date TIMESTAMPTZ,
    json_7256_list TEXT,
    statue_type INTEGER,
    statue INTEGER,
    statue_type_individual INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_puantaj_hash ON workcube_mikrolink.employees_puantaj (content_hash);
CREATE INDEX idx_employees_puantaj_lineage ON workcube_mikrolink.employees_puantaj (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_PUANTAJ_ROWS
CREATE TABLE workcube_mssql_raw.employees_puantaj_rows (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_puantaj_rows_run ON workcube_mssql_raw.employees_puantaj_rows (run_id);

-- EMPLOYEES_PUANTAJ_ROWS (canonical, used by: hr-bordro-detay, hr-compensation-detay, rowCount=153950)
CREATE TABLE workcube_mikrolink.employees_puantaj_rows (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    puantaj_id INTEGER NOT NULL,
    employee_puantaj_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id INTEGER,
    ssk_no VARCHAR(50),
    salary_type INTEGER,
    salary DOUBLE PRECISION,
    money VARCHAR(43),
    damga_vergisi_matrah DOUBLE PRECISION,
    cocuk_parasi DOUBLE PRECISION,
    sunday_count INTEGER,
    izinli_sunday_count INTEGER,
    paid_izinli_sunday_count INTEGER,
    offdays_count INTEGER,
    offdays_sunday_count INTEGER,
    total_days DOUBLE PRECISION,
    total_hours DOUBLE PRECISION,
    ssk_matrah DOUBLE PRECISION,
    damga_vergisi DOUBLE PRECISION,
    gelir_vergisi_matrah DOUBLE PRECISION,
    gelir_vergisi DOUBLE PRECISION,
    kumulatif_gelir_matrah DOUBLE PRECISION,
    ext_total_hours_0 DOUBLE PRECISION,
    ext_total_hours_1 DOUBLE PRECISION,
    ext_total_hours_2 DOUBLE PRECISION,
    ext_total_hours_3 DOUBLE PRECISION,
    vergi_indirimi DOUBLE PRECISION,
    vergi_indirimi_5084 DOUBLE PRECISION,
    ozel_kesinti DOUBLE PRECISION,
    ozel_kesinti_2 DOUBLE PRECISION,
    sakatlik_indirimi DOUBLE PRECISION,
    total_salary DOUBLE PRECISION,
    ext_salary DOUBLE PRECISION,
    gocmen_indirimi DOUBLE PRECISION,
    vergi_iadesi DOUBLE PRECISION,
    vergi_iade_damga_vergisi DOUBLE PRECISION,
    ssk_isveren_carpan DOUBLE PRECISION,
    ssk_isci_carpan DOUBLE PRECISION,
    issizlik_isveren_hissesi DOUBLE PRECISION,
    toplam_yuvarlama DOUBLE PRECISION,
    issizlik_isci_hissesi DOUBLE PRECISION,
    issizlik_isci_carpan DOUBLE PRECISION,
    tax_ratio DOUBLE PRECISION,
    ssdf_isveren_hissesi DOUBLE PRECISION,
    ssdf_isci_hissesi DOUBLE PRECISION,
    ssk_isci_hissesi DOUBLE PRECISION,
    ssk_isveren_hissesi DOUBLE PRECISION,
    net_ucret DOUBLE PRECISION,
    total_pay_ssk_tax DOUBLE PRECISION,
    total_pay_ssk DOUBLE PRECISION,
    total_pay_tax DOUBLE PRECISION,
    total_pay DOUBLE PRECISION,
    kidem_worker DOUBLE PRECISION,
    kidem_boss DOUBLE PRECISION,
    gross_net BOOLEAN,
    izin DOUBLE PRECISION,
    izin_count DOUBLE PRECISION,
    trade_union_deduction DOUBLE PRECISION,
    avans DOUBLE PRECISION,
    izin_paid DOUBLE PRECISION,
    izin_paid_count DOUBLE PRECISION,
    kidem_amount DOUBLE PRECISION,
    ihbar_amount DOUBLE PRECISION,
    yillik_izin_amount DOUBLE PRECISION,
    ssk_matrah_salary DOUBLE PRECISION,
    gvm_izin DOUBLE PRECISION,
    gvm_ihbar DOUBLE PRECISION,
    ssk_work_hours DOUBLE PRECISION,
    update_date TIMESTAMPTZ,
    update_ip VARCHAR(50),
    update_emp INTEGER,
    read_date TIMESTAMPTZ,
    mahsup_g_vergisi DOUBLE PRECISION,
    days_506 INTEGER,
    in_out_id INTEGER,
    ssk_isveren_hissesi_gov DOUBLE PRECISION,
    ssk_devir DOUBLE PRECISION,
    ssk_devir_last DOUBLE PRECISION,
    emp_bank_id INTEGER,
    ssk_isci_hissesi_dusulecek DOUBLE PRECISION,
    issizlik_isci_hissesi_dusulecek DOUBLE PRECISION,
    vergi_istisna_ssk_net DOUBLE PRECISION,
    vergi_istisna_ssk DOUBLE PRECISION,
    vergi_istisna_vergi DOUBLE PRECISION,
    vergi_istisna_vergi_net DOUBLE PRECISION,
    vergi_istisna_damga DOUBLE PRECISION,
    vergi_istisna_damga_net DOUBLE PRECISION,
    vergi_istisna_total DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_100 DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_80 DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_60 DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_40 DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_20 DOUBLE PRECISION,
    ssk_isveren_hissesi_gov_100_day INTEGER,
    ssk_isveren_hissesi_gov_80_day INTEGER,
    ssk_isveren_hissesi_gov_60_day INTEGER,
    ssk_isveren_hissesi_gov_40_day INTEGER,
    ssk_isveren_hissesi_gov_20_day INTEGER,
    yillik_izin_amount_net DOUBLE PRECISION,
    ssk_isveren_hissesi_5921 DOUBLE PRECISION,
    ssk_isveren_hissesi_5510 DOUBLE PRECISION,
    ssk_isveren_hissesi_5084 DOUBLE PRECISION,
    ssk_isveren_hissesi_5921_day INTEGER,
    gelir_vergisi_indirimi_5746 DOUBLE PRECISION,
    ssk_isveren_hissesi_5746 DOUBLE PRECISION,
    expense_code VARCHAR(50),
    account_code VARCHAR(50),
    account_bill_type INTEGER,
    row_department_head VARCHAR(200),
    is_kismi_istihdam BOOLEAN,
    total_salary_hours DOUBLE PRECISION,
    ihbar_amount_net DOUBLE PRECISION,
    ext_total_hours_5 DOUBLE PRECISION,
    sunday_count_hour DOUBLE PRECISION,
    izinli_sunday_count_hour DOUBLE PRECISION,
    paid_izinli_sunday_count_hour DOUBLE PRECISION,
    offdays_count_hour DOUBLE PRECISION,
    offdays_sunday_count_hour DOUBLE PRECISION,
    work_day_hour DOUBLE PRECISION,
    ssk_isveren_hissesi_6111 DOUBLE PRECISION,
    absent_days INTEGER,
    ssk_days INTEGER,
    ssk_matrah_exemption DOUBLE PRECISION,
    tax_matrah_exemption DOUBLE PRECISION,
    tax_matrah_exemption_get_all DOUBLE PRECISION,
    tax_matrah_exemption_get DOUBLE PRECISION,
    position_branch_id INTEGER,
    position_department_id INTEGER,
    position_code INTEGER,
    position_name VARCHAR(100),
    upper_position_code INTEGER,
    upper_position_code2 INTEGER,
    upper_position_name VARCHAR(100),
    upper_position_name2 VARCHAR(100),
    upper_position_employee VARCHAR(200),
    upper_position_employee2 VARCHAR(200),
    upper_position_employee_id INTEGER,
    upper_position_employee_id2 INTEGER,
    position_cat_id INTEGER,
    title_id INTEGER,
    func_id INTEGER,
    ext_salary_net DOUBLE PRECISION,
    half_offtime_day_total DOUBLE PRECISION,
    half_offtime_total_hour DOUBLE PRECISION,
    half_offtime_day_total_net DOUBLE PRECISION,
    yillik_izin_amount_gelir_vergisi DOUBLE PRECISION,
    yillik_izin_amount_damga_vergisi DOUBLE PRECISION,
    yillik_izin_amount_ssk_isveren_hissesi DOUBLE PRECISION,
    yillik_izin_amount_ssk_isci_hissesi DOUBLE PRECISION,
    yillik_izin_amount_ssk_isveren_issizlik DOUBLE PRECISION,
    yillik_izin_amount_ssk_isci_issizlik DOUBLE PRECISION,
    ihbar_amount_gelir_vergisi DOUBLE PRECISION,
    ihbar_amount_damga_vergisi DOUBLE PRECISION,
    kidem_amount_net DOUBLE PRECISION,
    kidem_amount_damga_vergisi DOUBLE PRECISION,
    department_id INTEGER,
    ssk_statute INTEGER,
    sabit_prim INTEGER,
    weekly_day DOUBLE PRECISION,
    weekly_hour DOUBLE PRECISION,
    weekend_day DOUBLE PRECISION,
    weekend_hour DOUBLE PRECISION,
    weekly_amount DOUBLE PRECISION,
    weekend_amount DOUBLE PRECISION,
    offdays_amount DOUBLE PRECISION,
    izin_amount DOUBLE PRECISION,
    izin_paid_amount DOUBLE PRECISION,
    izin_sunday_paid_amount DOUBLE PRECISION,
    ext_total_hours_0_amount DOUBLE PRECISION,
    ext_total_hours_1_amount DOUBLE PRECISION,
    ext_total_hours_2_amount DOUBLE PRECISION,
    ext_total_hours_5_amount DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    ssk_amount DOUBLE PRECISION,
    ssk_isveren_hissesi_6486 DOUBLE PRECISION,
    ssk_isveren_hissesi_6322 DOUBLE PRECISION,
    tax_account_style INTEGER,
    ssk_isci_hissesi_6322 DOUBLE PRECISION,
    ssk_iseveren_hissesi_25510 DOUBLE PRECISION,
    ssk_isveren_hissesi_25510 DOUBLE PRECISION,
    is_5746_control BOOLEAN,
    ssk_isveren_hissesi_14857 DOUBLE PRECISION,
    bes_isci_carpan DOUBLE PRECISION,
    bes_isci_hissesi DOUBLE PRECISION,
    organization_step_id INTEGER,
    gelir_vergisi_indirimi_4691 DOUBLE PRECISION,
    ssk_isveren_hissesi_4691 DOUBLE PRECISION,
    is_4691_control BOOLEAN,
    kismi_istihdam_gun INTEGER,
    kismi_istihdam_saat DOUBLE PRECISION,
    ssk_isveren_hissesi_6645 DOUBLE PRECISION,
    ssk_isveren_hissesi_46486 DOUBLE PRECISION,
    ssk_isveren_hissesi_56486 DOUBLE PRECISION,
    ssk_isveren_hissesi_66486 DOUBLE PRECISION,
    issizlik_isveren_hissesi_687 DOUBLE PRECISION,
    issizlik_isci_hissesi_687 DOUBLE PRECISION,
    ssk_isci_hissesi_687 DOUBLE PRECISION,
    ssk_isveren_hissesi_687 DOUBLE PRECISION,
    gelir_vergisi_indirimi_687 DOUBLE PRECISION,
    damga_vergisi_indirimi_687 DOUBLE PRECISION,
    ssk_isveren_hissesi_7103 DOUBLE PRECISION,
    ssk_isci_hissesi_7103 DOUBLE PRECISION,
    issizlik_isci_hissesi_7103 DOUBLE PRECISION,
    issizlik_isveren_hissesi_7103 DOUBLE PRECISION,
    gelir_vergisi_indirimi_7103 DOUBLE PRECISION,
    damga_vergisi_indirimi_7103 DOUBLE PRECISION,
    law_number_7103 INTEGER,
    salary_enc VARCHAR(250),
    damga_vergisi_matrah_enc VARCHAR(250),
    kumulatif_gelir_matrah_enc VARCHAR(250),
    total_salary_enc VARCHAR(250),
    total_amount_enc VARCHAR(250),
    net_ucret_enc VARCHAR(250),
    weekly_amount_enc VARCHAR(250),
    weekend_amount_enc VARCHAR(250),
    offdays_amount_enc VARCHAR(250),
    ssk_matrah_rd_out DOUBLE PRECISION,
    ssk_days_5746 INTEGER,
    damga_vergisi_indirimi_5746 DOUBLE PRECISION,
    total_time_tax DOUBLE PRECISION,
    total_time_arge DOUBLE PRECISION,
    damga_vergisi_matrah_5746 DOUBLE PRECISION,
    gelir_vergisi_matrah_5746 DOUBLE PRECISION,
    ssk_matrah_5746 DOUBLE PRECISION,
    gelir_vergisi_matrah_enc VARCHAR(250),
    tax_days_5746 DOUBLE PRECISION,
    short_working_calc DOUBLE PRECISION,
    ozel_kesinti_2_net_fark DOUBLE PRECISION,
    gvm_matrah_5746 DOUBLE PRECISION,
    ssk_isveren_hissesi_7252 DOUBLE PRECISION,
    ssk_isci_hissesi_7252 DOUBLE PRECISION,
    issizlik_isci_hissesi_7252 DOUBLE PRECISION,
    issizlik_isveren_hissesi_7252 DOUBLE PRECISION,
    law_number_7252 INTEGER,
    ssk_days_7252 DOUBLE PRECISION,
    is_7252_control BOOLEAN,
    ozel_kesinti_2_net DOUBLE PRECISION,
    ssk_isveren_hissesi_7256 DOUBLE PRECISION,
    ssk_isci_hissesi_7256 DOUBLE PRECISION,
    issizlik_isci_hissesi_7256 DOUBLE PRECISION,
    issizlik_isveren_hissesi_7256 DOUBLE PRECISION,
    base_amount_7256 DOUBLE PRECISION,
    is_7256_plus BOOLEAN,
    stampduty_5746 DOUBLE PRECISION,
    ssk_isveren_hissesi_3294 DOUBLE PRECISION,
    past_agi_day_payroll DOUBLE PRECISION,
    daily_minimum_wage_base_cumulate DOUBLE PRECISION,
    minimum_wage_cumulative DOUBLE PRECISION,
    daily_minimum_income_tax DOUBLE PRECISION,
    daily_minimum_wage_stamp_tax DOUBLE PRECISION,
    daily_minimum_wage DOUBLE PRECISION,
    stamp_tax_temp DOUBLE PRECISION,
    income_tax_temp DOUBLE PRECISION,
    health_insurance_premium_worker DOUBLE PRECISION,
    death_insurance_premium_worker DOUBLE PRECISION,
    death_insurance_premium_employer DOUBLE PRECISION,
    short_term_premium_employer DOUBLE PRECISION,
    health_insurance_premium_employer DOUBLE PRECISION,
    json_7256_list TEXT,
    ext_total_hours_8 DOUBLE PRECISION,
    ext_total_hours_9 DOUBLE PRECISION,
    ext_total_hours_10 DOUBLE PRECISION,
    ext_total_hours_11 DOUBLE PRECISION,
    ext_total_hours_12 DOUBLE PRECISION,
    ext_total_hours_8_amount DOUBLE PRECISION,
    ext_total_hours_9_amount DOUBLE PRECISION,
    ext_total_hours_10_amount DOUBLE PRECISION,
    ext_total_hours_11_amount DOUBLE PRECISION,
    ext_total_hours_12_amount DOUBLE PRECISION,
    akdi_day DOUBLE PRECISION,
    akdi_hour DOUBLE PRECISION,
    akdi_amount DOUBLE PRECISION,
    seniority_salary DOUBLE PRECISION,
    ssk_transfer_amount DOUBLE PRECISION,
    ssk_isveren_hissesi_15510 DOUBLE PRECISION,
    project_id INTEGER,
    b_salary DOUBLE PRECISION,
    b_salary_net DOUBLE PRECISION,
    row_calc_detail TEXT,
    damga_vergisi_indirimi_4691 DOUBLE PRECISION,
    sgk_isveren_indirimi_2828 DOUBLE PRECISION,
    sgk_isci_indirimi_2828 DOUBLE PRECISION,
    sgk_issizlik_isveren_indirimi_2828 DOUBLE PRECISION,
    sgk_issizlik_isci_indirimi_2828 DOUBLE PRECISION,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_puantaj_rows_hash ON workcube_mikrolink.employees_puantaj_rows (content_hash);
CREATE INDEX idx_employees_puantaj_rows_lineage ON workcube_mikrolink.employees_puantaj_rows (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_SALARY
CREATE TABLE workcube_mssql_raw.employees_salary (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_salary_run ON workcube_mssql_raw.employees_salary (run_id);

-- EMPLOYEES_SALARY (canonical, used by: hr-maas-raporu, rowCount=26001)
CREATE TABLE workcube_mikrolink.employees_salary (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    salary_history_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_id INTEGER NOT NULL,
    period_year INTEGER NOT NULL,
    money VARCHAR(43),
    m1 DOUBLE PRECISION,
    m2 DOUBLE PRECISION,
    m3 DOUBLE PRECISION,
    m4 DOUBLE PRECISION,
    m5 DOUBLE PRECISION,
    m6 DOUBLE PRECISION,
    m7 DOUBLE PRECISION,
    m8 DOUBLE PRECISION,
    m9 DOUBLE PRECISION,
    m10 DOUBLE PRECISION,
    m11 DOUBLE PRECISION,
    m12 DOUBLE PRECISION,
    record_date TIMESTAMPTZ NOT NULL,
    record_ip VARCHAR(50),
    record_emp INTEGER NOT NULL,
    update_date TIMESTAMPTZ,
    update_ip VARCHAR(50),
    update_emp INTEGER,
    in_out_id INTEGER,
    salary_code VARCHAR(100),
    m1_enc VARCHAR(250),
    m2_enc VARCHAR(250),
    m3_enc VARCHAR(250),
    m4_enc VARCHAR(250),
    m5_enc VARCHAR(250),
    m6_enc VARCHAR(250),
    m7_enc VARCHAR(250),
    m8_enc VARCHAR(250),
    m9_enc VARCHAR(250),
    m10_enc VARCHAR(250),
    m11_enc VARCHAR(250),
    m12_enc VARCHAR(250),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_salary_hash ON workcube_mikrolink.employees_salary (content_hash);
CREATE INDEX idx_employees_salary_lineage ON workcube_mikrolink.employees_salary (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEES_SALARY_HISTORY
CREATE TABLE workcube_mssql_raw.employees_salary_history (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employees_salary_history_run ON workcube_mssql_raw.employees_salary_history (run_id);

-- EMPLOYEES_SALARY_HISTORY (canonical, used by: hr-maas-gecmisi, rowCount=29529)
CREATE TABLE workcube_mikrolink.employees_salary_history (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    employee_id INTEGER NOT NULL,
    history_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    period_year INTEGER,
    money VARCHAR(43),
    m1 DOUBLE PRECISION,
    m2 DOUBLE PRECISION,
    m3 DOUBLE PRECISION,
    m4 DOUBLE PRECISION,
    m5 DOUBLE PRECISION,
    m6 DOUBLE PRECISION,
    m7 DOUBLE PRECISION,
    m8 DOUBLE PRECISION,
    m9 DOUBLE PRECISION,
    m10 DOUBLE PRECISION,
    m11 DOUBLE PRECISION,
    m12 DOUBLE PRECISION,
    salary_update_id INTEGER,
    record_date TIMESTAMPTZ,
    record_ip VARCHAR(50),
    record_emp INTEGER,
    in_out_id INTEGER,
    salary_code VARCHAR(100),
    m1_enc VARCHAR(250),
    m2_enc VARCHAR(250),
    m3_enc VARCHAR(250),
    m4_enc VARCHAR(250),
    m5_enc VARCHAR(250),
    m6_enc VARCHAR(250),
    m7_enc VARCHAR(250),
    m8_enc VARCHAR(250),
    m9_enc VARCHAR(250),
    m10_enc VARCHAR(250),
    m11_enc VARCHAR(250),
    m12_enc VARCHAR(250),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employees_salary_history_hash ON workcube_mikrolink.employees_salary_history (content_hash);
CREATE INDEX idx_employees_salary_history_lineage ON workcube_mikrolink.employees_salary_history (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEE_DAILY_IN_OUT
CREATE TABLE workcube_mssql_raw.employee_daily_in_out (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employee_daily_in_out_run ON workcube_mssql_raw.employee_daily_in_out (run_id);

-- EMPLOYEE_DAILY_IN_OUT (canonical, used by: hr-puantaj, rowCount=106390)
CREATE TABLE workcube_mikrolink.employee_daily_in_out (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    row_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    file_id INTEGER,
    employee_id INTEGER,
    in_out_id INTEGER,
    branch_id INTEGER,
    start_date TIMESTAMPTZ,
    finish_date TIMESTAMPTZ,
    record_date TIMESTAMPTZ,
    record_ip VARCHAR(50),
    record_emp INTEGER,
    day_type INTEGER,
    detail TEXT,
    file2_id INTEGER,
    special_code VARCHAR(200),
    is_week_rest_day INTEGER,
    is_puantaj_off BOOLEAN,
    related_code VARCHAR(50),
    created_code VARCHAR(50),
    is_off_day BOOLEAN,
    partner_id INTEGER,
    update_date TIMESTAMPTZ,
    update_ip VARCHAR(50),
    update_emp INTEGER,
    allowance_id INTEGER,
    ssk_statue INTEGER,
    statue_type INTEGER,
    total_work_hour DOUBLE PRECISION,
    daily_working_hour DOUBLE PRECISION,
    from_hourly_addfare BOOLEAN,
    paper_no VARCHAR(15),
    is_akdi_day INTEGER,
    in_coordinate1 VARCHAR(50),
    out_coordinate2 VARCHAR(50),
    out_coordinate1 VARCHAR(50),
    in_coordinate2 VARCHAR(50),
    project_id INTEGER,
    work_id INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employee_daily_in_out_hash ON workcube_mikrolink.employee_daily_in_out (content_hash);
CREATE INDEX idx_employee_daily_in_out_lineage ON workcube_mikrolink.employee_daily_in_out (source_schema, source_table, source_pk);

-- raw staging: EMPLOYEE_POSITIONS
CREATE TABLE workcube_mssql_raw.employee_positions (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_employee_positions_run ON workcube_mssql_raw.employee_positions (run_id);

-- EMPLOYEE_POSITIONS (canonical, used by: hr-compensation-detay, hr-personel-listesi, rowCount=11685)
CREATE TABLE workcube_mikrolink.employee_positions (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    position_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    position_cat_id INTEGER,
    t_id INTEGER,
    first_position_code INTEGER,
    upper_position_code INTEGER,
    upper_position_code2 INTEGER,
    is_master BOOLEAN,
    position_code INTEGER NOT NULL,
    employee_id INTEGER,
    employee_name VARCHAR(50),
    employee_surname VARCHAR(50),
    employee_email VARCHAR(50),
    position_name VARCHAR(100),
    position_status BOOLEAN,
    detail VARCHAR(100),
    department_id INTEGER,
    level_id VARCHAR(500),
    level_extra_id VARCHAR(500),
    user_group_id VARCHAR(50),
    valid INTEGER,
    valid_member INTEGER,
    validator_member INTEGER,
    valid_date TIMESTAMPTZ,
    ongr_ucret DOUBLE PRECISION,
    money_id INTEGER,
    aciklama1 VARCHAR(50),
    aciklama2 VARCHAR(50),
    aciklama3 VARCHAR(50),
    aciklama4 VARCHAR(50),
    aciklama5 VARCHAR(50),
    rakam1 DOUBLE PRECISION,
    rakam2 DOUBLE PRECISION,
    rakam3 DOUBLE PRECISION,
    rakam4 DOUBLE PRECISION,
    rakam5 DOUBLE PRECISION,
    on_maliyet DOUBLE PRECISION,
    on_hour DOUBLE PRECISION,
    pos_ent_detail VARCHAR(150),
    announce_com BOOLEAN,
    announce_public BOOLEAN,
    ehesap BOOLEAN,
    is_vekaleten BOOLEAN,
    vekaleten_date TIMESTAMPTZ,
    period_id INTEGER,
    title_id INTEGER,
    hierarchy VARCHAR(200),
    update_emp INTEGER,
    update_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    admin_status BOOLEAN,
    ozel_kod VARCHAR(50),
    is_critical BOOLEAN,
    organization_step_id INTEGER,
    on_maliyet_yil DOUBLE PRECISION,
    is_org_view BOOLEAN,
    collar_type INTEGER,
    func_id INTEGER,
    branch_id INTEGER,
    our_company_id INTEGER,
    in_company_reason_id INTEGER,
    power_user BOOLEAN,
    power_user_level_id VARCHAR(500),
    discount_valid BOOLEAN,
    price_display_valid BOOLEAN,
    cost_display_valid BOOLEAN,
    dynamic_hierarchy VARCHAR(200),
    dynamic_hierarchy_add VARCHAR(50),
    consumer_priority BOOLEAN,
    price_valid BOOLEAN,
    position_stage INTEGER,
    member_view_control BOOLEAN,
    member_direct_denied BOOLEAN,
    on_hour_daily DOUBLE PRECISION,
    duedate_valid BOOLEAN,
    is_observation BOOLEAN,
    observation_date TIMESTAMPTZ,
    is_trial BOOLEAN,
    trial_date TIMESTAMPTZ,
    rate_valid BOOLEAN,
    time_cost_control BOOLEAN,
    wrk_menu VARCHAR(50),
    their_records_only BOOLEAN,
    report_user_level VARCHAR(500),
    sensitive_user_level VARCHAR(500),
    data_level VARCHAR(500),
    citys VARCHAR(500),
    sub_role_model BOOLEAN,
    upper_position_code_real INTEGER,
    ust_grup_id INTEGER,
    fonksiyon_id INTEGER,
    alt_birim_id INTEGER,
    task_our_company INTEGER,
    country_id INTEGER,
    county_id INTEGER,
    disable_cache BOOLEAN,
    workstation_view_control BOOLEAN,
    wai VARCHAR(250),
    project_id INTEGER,
    title_name VARCHAR(255),
    position_section_id INTEGER,
    position_unit_id INTEGER,
    position_lower_unit_id INTEGER,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_employee_positions_hash ON workcube_mikrolink.employee_positions (content_hash);
CREATE INDEX idx_employee_positions_lineage ON workcube_mikrolink.employee_positions (source_schema, source_table, source_pk);

-- ===== EXPENSE_ITEMS (PARAMETRIC — placeholder) =====
-- Used by: fin-masraf-detay
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.expense_items (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_expense_items_run ON workcube_mssql_raw.expense_items (run_id);

-- workcube_mikrolink.expense_items TODO Faz 16.2.P

-- ===== EXPENSE_ITEM_PLANS (PARAMETRIC — placeholder) =====
-- Used by: fin-masraf-detay, fin-tutar-mutabakat
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.expense_item_plans (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_expense_item_plans_run ON workcube_mssql_raw.expense_item_plans (run_id);

-- workcube_mikrolink.expense_item_plans TODO Faz 16.2.P

-- ===== INVOICE (PARAMETRIC — placeholder) =====
-- Used by: fin-fatura-satirlari, fin-faturalar, fin-tutar-mutabakat
-- Schemas: workcube_mikrolink_1, {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.invoice (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_invoice_run ON workcube_mssql_raw.invoice (run_id);

-- workcube_mikrolink.invoice TODO Faz 16.2.P

-- ===== INVOICE_ROW (PARAMETRIC — placeholder) =====
-- Used by: fin-fatura-satirlari
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.invoice_row (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_invoice_row_run ON workcube_mssql_raw.invoice_row (run_id);

-- workcube_mikrolink.invoice_row TODO Faz 16.2.P

-- raw staging: MONEY_HISTORY
CREATE TABLE workcube_mssql_raw.money_history (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_money_history_run ON workcube_mssql_raw.money_history (run_id);

-- MONEY_HISTORY (canonical, used by: fin-muhasebe-detay, rowCount=180995)
CREATE TABLE workcube_mikrolink.money_history (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    money_history_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    money VARCHAR(43),
    rate1 DOUBLE PRECISION,
    rate2 DOUBLE PRECISION,
    rate3 DOUBLE PRECISION,
    validate_date TIMESTAMPTZ,
    validate_hour VARCHAR(43),
    validate_s_hour VARCHAR(43),
    company_id INTEGER,
    period_id INTEGER,
    ratepp2 DOUBLE PRECISION,
    ratepp3 DOUBLE PRECISION,
    rateww2 DOUBLE PRECISION,
    rateww3 DOUBLE PRECISION,
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    effective_sale DOUBLE PRECISION,
    effective_pur DOUBLE PRECISION,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_money_history_hash ON workcube_mikrolink.money_history (content_hash);
CREATE INDEX idx_money_history_lineage ON workcube_mikrolink.money_history (source_schema, source_table, source_pk);

-- raw staging: OFFTIME
CREATE TABLE workcube_mssql_raw.offtime (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_offtime_run ON workcube_mssql_raw.offtime (run_id);

-- OFFTIME (canonical, used by: hr-izin-raporu, rowCount=73684)
CREATE TABLE workcube_mikrolink.offtime (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    valid BOOLEAN,
    employee_id INTEGER NOT NULL,
    offtime_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    offtimecat_id INTEGER,
    validator_position_code INTEGER,
    valid_employee_id INTEGER,
    validdate TIMESTAMPTZ,
    detail VARCHAR(500),
    startdate TIMESTAMPTZ NOT NULL,
    finishdate TIMESTAMPTZ,
    work_startdate TIMESTAMPTZ,
    total_hours INTEGER,
    tel_code VARCHAR(43),
    tel_no VARCHAR(43),
    address VARCHAR(300),
    record_date TIMESTAMPTZ NOT NULL,
    record_emp INTEGER NOT NULL,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    deserve_date TIMESTAMPTZ,
    is_puantaj_off BOOLEAN,
    valid_1 BOOLEAN,
    validator_position_code_1 INTEGER,
    valid_employee_id_1 INTEGER,
    validdate_1 TIMESTAMPTZ,
    valid_2 BOOLEAN,
    validator_position_code_2 INTEGER,
    valid_employee_id_2 INTEGER,
    validdate_2 TIMESTAMPTZ,
    emp_valid BOOLEAN,
    emp_valid_id INTEGER,
    emp_valid_date TIMESTAMPTZ,
    is_added_offtime BOOLEAN,
    added_offtime_id INTEGER,
    valid_1_detail VARCHAR(500),
    valid_2_detail VARCHAR(500),
    offtime_stage INTEGER,
    in_out_id INTEGER,
    special_code VARCHAR(200),
    is_from_pdks BOOLEAN,
    pdks_file_id INTEGER,
    is_plan BOOLEAN,
    file_name VARCHAR(250),
    is_approval INTEGER,
    is_cancel BOOLEAN,
    sub_offtimecat_id INTEGER,
    short_working_rate INTEGER,
    first_week_calculation BOOLEAN,
    short_working_hours DOUBLE PRECISION,
    __is_examination BOOLEAN,
    __is_bus_ticket BOOLEAN,
    __is_housing BOOLEAN,
    __is_comp BOOLEAN,
    __is_otel BOOLEAN,
    __is_home BOOLEAN,
    __is_self BOOLEAN,
    __is_flight_ticket BOOLEAN,
    week_offday INTEGER,
    document_number VARCHAR(50),
    is_source_app BOOLEAN,
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_offtime_hash ON workcube_mikrolink.offtime (content_hash);
CREATE INDEX idx_offtime_lineage ON workcube_mikrolink.offtime (source_schema, source_table, source_pk);

-- WARNING: ORDERS no snapshot columns — skipped

-- WARNING: ORDER_ROW no snapshot columns — skipped

-- raw staging: OUR_COMPANY
CREATE TABLE workcube_mssql_raw.our_company (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_our_company_run ON workcube_mssql_raw.our_company (run_id);

-- OUR_COMPANY (canonical, used by: hr-compensation-detay, rowCount=42)
CREATE TABLE workcube_mikrolink.our_company (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    comp_id INTEGER NOT NULL,
    company_name VARCHAR(200),
    nick_name VARCHAR(50),
    tax_office VARCHAR(50),
    tax_no VARCHAR(50),
    tel_code VARCHAR(43),
    tel VARCHAR(43),
    fax VARCHAR(43),
    manager VARCHAR(40),
    manager_position_code INTEGER,
    manager_position_code2 INTEGER,
    web VARCHAR(50),
    email VARCHAR(50),
    address TEXT,
    admin_mail TEXT,
    tel2 VARCHAR(43),
    tel3 VARCHAR(43),
    tel4 VARCHAR(43),
    fax2 VARCHAR(43),
    t_no VARCHAR(50),
    sermaye VARCHAR(43),
    chamber VARCHAR(150),
    chamber_no VARCHAR(50),
    chamber2 VARCHAR(150),
    chamber2_no VARCHAR(50),
    asset_file_name1 VARCHAR(100),
    asset_file_name1_server_id INTEGER,
    asset_file_name2 VARCHAR(100),
    asset_file_name2_server_id INTEGER,
    asset_file_name3 VARCHAR(100),
    asset_file_name3_server_id INTEGER,
    headquarters_id INTEGER,
    is_organization BOOLEAN,
    hierarchy VARCHAR(75),
    hierarchy2 VARCHAR(75),
    comp_status BOOLEAN,
    record_emp INTEGER,
    record_date TIMESTAMPTZ,
    record_ip VARCHAR(50),
    update_emp INTEGER,
    update_date TIMESTAMPTZ,
    update_ip VARCHAR(50),
    authority_doc_finish TIMESTAMPTZ,
    authority_doc_start TIMESTAMPTZ,
    authority_doc_number VARCHAR(100),
    authority_doc_type VARCHAR(50),
    authority_doc_warning INTEGER,
    coordinate_1 VARCHAR(50),
    coordinate_2 VARCHAR(50),
    country_id INTEGER,
    postal_code VARCHAR(50),
    city_id INTEGER,
    city_subdivision_name VARCHAR(50),
    building_number VARCHAR(50),
    street_name VARCHAR(50),
    district_name VARCHAR(50),
    county_id INTEGER,
    mersis_no VARCHAR(50),
    nace_code VARCHAR(50),
    mail_server VARCHAR(250),
    smtp_port INTEGER,
    mail_username VARCHAR(150),
    mail_password VARCHAR(50),
    accounter_key VARCHAR(100),
    kep_adress VARCHAR(50),
    finance_mail VARCHAR(50),
    finance_mail_cc VARCHAR(250),
    company_short_code VARCHAR(20),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_our_company_hash ON workcube_mikrolink.our_company (content_hash);
CREATE INDEX idx_our_company_lineage ON workcube_mikrolink.our_company (source_schema, source_table, source_pk);

-- raw staging: PRO_PROJECTS
CREATE TABLE workcube_mssql_raw.pro_projects (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_pro_projects_run ON workcube_mssql_raw.pro_projects (run_id);

-- PRO_PROJECTS (canonical, used by: fin-cari-islemler, fin-fatura-satirlari, fin-masraf-detay, rowCount=29140)
CREATE TABLE workcube_mikrolink.pro_projects (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    project_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_number VARCHAR(50),
    project_status BOOLEAN,
    project_emp_id INTEGER,
    project_head VARCHAR(100) NOT NULL,
    agreement_no VARCHAR(43),
    project_detail TEXT,
    target_start TIMESTAMPTZ,
    target_finish TIMESTAMPTZ,
    pro_currency_id INTEGER,
    pro_priority_id INTEGER,
    outsrc_cmp_id INTEGER,
    outsrc_partner_id INTEGER,
    project_target VARCHAR(250),
    expense_code VARCHAR(50),
    expected_budget DOUBLE PRECISION,
    expected_cost DOUBLE PRECISION,
    budget_currency VARCHAR(43),
    cost_currency VARCHAR(43),
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_par INTEGER,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_par INTEGER,
    update_ip VARCHAR(50),
    campaign_id INTEGER,
    company_id INTEGER,
    consumer_id INTEGER,
    partner_id INTEGER,
    related_project_id INTEGER,
    process_cat INTEGER,
    project_folder VARCHAR(250),
    workgroup_id INTEGER,
    product_id INTEGER,
    department_id INTEGER,
    country_id INTEGER,
    sales_zone_id INTEGER,
    location_id INTEGER,
    special_definition_id INTEGER,
    cargo_company_id INTEGER,
    duty_company_id INTEGER,
    insurance_company_id INTEGER,
    term_date TIMESTAMPTZ,
    estimated_out_date TIMESTAMPTZ,
    estimated_arrive_date TIMESTAMPTZ,
    county_id INTEGER,
    city_id INTEGER,
    coordinate_1 VARCHAR(50),
    coordinate_2 VARCHAR(50),
    project_pos_code INTEGER,
    work_order_number VARCHAR(250),
    main_sales_area_id INTEGER,
    special_sector INTEGER,
    special_two_g INTEGER,
    special_three_g INTEGER,
    special_lte INTEGER,
    is_send_webservice BOOLEAN,
    branch_id INTEGER,
    language_id INTEGER,
    google_project_folder_id VARCHAR(200),
    image_size INTEGER,
    img_path VARCHAR(500),
    img_name VARCHAR(500),
    img_detail VARCHAR(1000),
    img_video_link BOOLEAN,
    img_video_path VARCHAR(500),
    img_language VARCHAR(50),
    is_external_link BOOLEAN,
    is_stepbystep_imp BOOLEAN,
    implementation_step_imported BOOLEAN,
    image_is_ai BOOLEAN,
    project_presentation TEXT,
    alt_birim_id VARCHAR(20),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_pro_projects_hash ON workcube_mikrolink.pro_projects (content_hash);
CREATE INDEX idx_pro_projects_lineage ON workcube_mikrolink.pro_projects (source_schema, source_table, source_pk);

-- raw staging: SETUP_DOCUMENT_TYPE
CREATE TABLE workcube_mssql_raw.setup_document_type (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_setup_document_type_run ON workcube_mssql_raw.setup_document_type (run_id);

-- SETUP_DOCUMENT_TYPE (canonical, used by: fin-muhasebe-detay, rowCount=20)
CREATE TABLE workcube_mikrolink.setup_document_type (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    document_type_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    document_type_name VARCHAR(100),
    document_type_detail VARCHAR(250),
    record_date TIMESTAMPTZ,
    record_emp INTEGER,
    record_ip VARCHAR(50),
    update_date TIMESTAMPTZ,
    update_emp INTEGER,
    update_ip VARCHAR(50),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_setup_document_type_hash ON workcube_mikrolink.setup_document_type (content_hash);
CREATE INDEX idx_setup_document_type_lineage ON workcube_mikrolink.setup_document_type (source_schema, source_table, source_pk);

-- WARNING: SETUP_PROCESS_CAT no snapshot columns — skipped

-- ===== STOCK_FIS (PARAMETRIC — placeholder) =====
-- Used by: fin-stok-fis-detay
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.stock_fis (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_stock_fis_run ON workcube_mssql_raw.stock_fis (run_id);

-- workcube_mikrolink.stock_fis TODO Faz 16.2.P

-- ===== STOCK_FIS_ROW (PARAMETRIC — placeholder) =====
-- Used by: fin-stok-fis-detay
-- Schemas: {schema}
-- TODO_PARAMETRIC_SCHEMA_SNAPSHOT_REQUIRED (Faz 16.2.P sprint sonrası generator rerun)
-- Bu tablo schema-service crawl'da workcube_mikrolink canonical değil, sub-schema (yıllık).
-- DDL Faz 16.2.P sonrası eklenir; şimdilik raw staging + audit hazır.

CREATE TABLE workcube_mssql_raw.stock_fis_row (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_stock_fis_row_run ON workcube_mssql_raw.stock_fis_row (run_id);

-- workcube_mikrolink.stock_fis_row TODO Faz 16.2.P

-- raw staging: TRAINING_CLASS_ATTENDER
CREATE TABLE workcube_mssql_raw.training_class_attender (
    run_id UUID NOT NULL,
    source_schema VARCHAR(128) NOT NULL,
    source_year SMALLINT,
    source_pk TEXT,
    raw_payload JSONB NOT NULL,
    extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_training_class_attender_run ON workcube_mssql_raw.training_class_attender (run_id);

-- TRAINING_CLASS_ATTENDER (canonical, used by: hr-egitim-katilim, rowCount=5615)
CREATE TABLE workcube_mikrolink.training_class_attender (
    source_schema VARCHAR(128) NOT NULL DEFAULT 'workcube_mikrolink',
    class_id INTEGER NOT NULL,
    emp_id INTEGER,
    comp_id INTEGER,
    par_id INTEGER,
    con_id INTEGER,
    grp_id INTEGER,
    status BOOLEAN,
    is_selfservice BOOLEAN,
    class_attender_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    detail VARCHAR(500),
    participation_rate DOUBLE PRECISION,
    comment VARCHAR(500),
    source_table VARCHAR(128) NOT NULL,
    source_pk TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    migration_row_id BIGSERIAL,  -- surrogate (PK metadata snapshot'ta yok, Codex iter-4)
    migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (migration_row_id),
    UNIQUE (source_schema, source_table, source_pk)
);

CREATE INDEX idx_training_class_attender_hash ON workcube_mikrolink.training_class_attender (content_hash);
CREATE INDEX idx_training_class_attender_lineage ON workcube_mikrolink.training_class_attender (source_schema, source_table, source_pk);


COMMIT;
