apiVersion: v1
kind: Service
metadata:
  name: ats-interview-evidence-ui
  labels:
    app: ats-interview-evidence-ui
spec:
  selector:
    app: ats-interview-evidence-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
