apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ethics-service-account.yaml
  - ethics-service-config.yaml
  - ethics-service-deployment.yaml
  - ethics-service.yaml
  - public-service-account.yaml
  - public-deployment.yaml
  - public-service.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: etik-speak
    includeTemplates: true
