apiVersion: v1
kind: ServiceAccount
metadata:
  name: etik-speak-manager
  labels:
    app.kubernetes.io/name: etik-speak-manager
automountServiceAccountToken: false
imagePullSecrets:
  - name: ghcr-pull
