apiVersion: v1
kind: Service
metadata:
  name: artifact-host
  labels:
    app.kubernetes.io/name: artifact-host
    app.kubernetes.io/component: artifact-host
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: artifact-host
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
